const $=id=>document.getElementById(id);
let currentView="dashboard",busy=false;
const TX={
ht:{brand:"Admin inik",message:"Mesaj",dashboard:"Rezime",approvals:"Demann / Kòmand",users:"Itilizatè",products:"Pwodwi",manual:"Operasyon manyèl",history:"Istorik",chat:"Chat sekirize",close:"Fèmen",allUsers:"Tout itilizatè yo",usersSub:"Non, imèl, telefòn, adrès, peyi, wòl, balans, UID, dènye aktivite ak estati an liy.",refresh:"Rafrechi",searchUsers:"Chèche non, imèl, telefòn oswa UID...",productInfo:"Enfòmasyon pwodwi yo",productSub:"Non vandè a parèt pou chak pwodwi.",approval:"Apwobasyon Admin",approvalSub:"Se sèlman admin ki ka valide/refize kòmand, depo ak retrè.",pendingWallet:"Depo / retrè an atant",ordersValidate:"Kòmand pou valide",privateChat:"Chat prive Admin ↔ Kliyan",privateSub:"Chwazi yon kliyan. Kliyan an pap wè idantite prive admin lan.",chooseClient:"— Chwazi kliyan —",openChat:"Louvri chat",writeAdmin:"Ekri mesaj admin...",send:"Voye",manualTitle:"Depo / Retrè admin",manualSub:"Anrejistre sèlman yon operasyon ou verifye oswa egzekite reyèlman andeyò aplikasyon an.",user:"Itilizatè",type:"Kalite",deposit:"Depo",withdrawal:"Retrè",amount:"Montan",currency:"Deviz",reference:"Referans / Nòt",saveOperation:"Anrejistre operasyon",historyTitle:"Istorik tranzaksyon",historySub:"Dat, lè, non, imèl, telefòn, UID, kalite, montan, referans ak estati.",allTransactions:"Tout tranzaksyon",exchange:"Echanj",ordersSales:"Kòmand / vant",allPeriods:"Tout dat",days7:"7 jou",days15:"15 jou",days30:"30 jou",days90:"90 jou",days365:"365 jou",allPeople:"Tout itilizatè / vandè"},
fr:{brand:"Admin unique",message:"Messages",dashboard:"Résumé",approvals:"Demandes / Commandes",users:"Utilisateurs",products:"Produits",manual:"Opérations manuelles",history:"Historique",chat:"Chat sécurisé",close:"Fermer",allUsers:"Tous les utilisateurs",usersSub:"Nom, e-mail, téléphone, adresse, pays, rôle, solde, UID, dernière activité et statut en ligne.",refresh:"Actualiser",searchUsers:"Rechercher nom, e-mail, téléphone ou UID...",productInfo:"Informations produits",productSub:"Le nom du vendeur apparaît pour chaque produit.",approval:"Approbation Admin",approvalSub:"Seul l’administrateur peut valider/refuser les commandes, dépôts et retraits.",pendingWallet:"Dépôts / retraits en attente",ordersValidate:"Commandes à valider",privateChat:"Chat privé Admin ↔ Client",privateSub:"Choisissez un client. Le client ne voit pas l’identité privée de l’administrateur.",chooseClient:"— Choisir un client —",openChat:"Ouvrir le chat",writeAdmin:"Écrire un message admin...",send:"Envoyer",manualTitle:"Dépôt / Retrait admin",manualSub:"Enregistrez uniquement une opération réellement vérifiée ou exécutée hors de l’application.",user:"Utilisateur",type:"Type",deposit:"Dépôt",withdrawal:"Retrait",amount:"Montant",currency:"Devise",reference:"Référence / Note",saveOperation:"Enregistrer l’opération",historyTitle:"Historique des transactions",historySub:"Date, heure, nom, e-mail, téléphone, UID, type, montant, référence et statut.",allTransactions:"Toutes les transactions",exchange:"Échange",ordersSales:"Commandes / ventes",allPeriods:"Toutes les dates",days7:"7 jours",days15:"15 jours",days30:"30 jours",days90:"90 jours",days365:"365 jours",allPeople:"Tous les utilisateurs / vendeurs"},
en:{brand:"Admin",message:"Messages",dashboard:"Overview",approvals:"Requests / Orders",users:"Users",products:"Products",manual:"Manual operations",history:"History",chat:"Secure chat",close:"Close",allUsers:"All users",usersSub:"Name, email, phone, address, country, role, balance, UID, last activity and online status.",refresh:"Refresh",searchUsers:"Search name, email, phone or UID...",productInfo:"Product information",productSub:"The seller name is shown for every product.",approval:"Admin Approval",approvalSub:"Only the administrator can approve/reject orders, deposits and withdrawals.",pendingWallet:"Pending deposits / withdrawals",ordersValidate:"Orders to validate",privateChat:"Private Admin ↔ Client Chat",privateSub:"Choose a client. The client does not see the administrator’s private identity.",chooseClient:"— Choose a client —",openChat:"Open chat",writeAdmin:"Write admin message...",send:"Send",manualTitle:"Admin Deposit / Withdrawal",manualSub:"Record only an operation actually verified or executed outside the application.",user:"User",type:"Type",deposit:"Deposit",withdrawal:"Withdrawal",amount:"Amount",currency:"Currency",reference:"Reference / Note",saveOperation:"Save operation",historyTitle:"Transaction history",historySub:"Date, time, name, email, phone, UID, type, amount, reference and status.",allTransactions:"All transactions",exchange:"Exchange",ordersSales:"Orders / sales",allPeriods:"All dates",days7:"7 days",days15:"15 days",days30:"30 days",days90:"90 days",days365:"365 days",allPeople:"All users / sellers"},
es:{brand:"Admin único",message:"Mensajes",dashboard:"Resumen",approvals:"Solicitudes / Pedidos",users:"Usuarios",products:"Productos",manual:"Operaciones manuales",history:"Historial",chat:"Chat seguro",close:"Cerrar",allUsers:"Todos los usuarios",usersSub:"Nombre, correo, teléfono, dirección, país, rol, saldo, UID, última actividad y estado en línea.",refresh:"Actualizar",searchUsers:"Buscar nombre, correo, teléfono o UID...",productInfo:"Información de productos",productSub:"El nombre del vendedor aparece en cada producto.",approval:"Aprobación Admin",approvalSub:"Solo el administrador puede aprobar/rechazar pedidos, depósitos y retiros.",pendingWallet:"Depósitos / retiros pendientes",ordersValidate:"Pedidos por validar",privateChat:"Chat privado Admin ↔ Cliente",privateSub:"Elija un cliente. El cliente no ve la identidad privada del administrador.",chooseClient:"— Elegir un cliente —",openChat:"Abrir chat",writeAdmin:"Escribir mensaje admin...",send:"Enviar",manualTitle:"Depósito / Retiro admin",manualSub:"Registre solo una operación realmente verificada o ejecutada fuera de la aplicación.",user:"Usuario",type:"Tipo",deposit:"Depósito",withdrawal:"Retiro",amount:"Monto",currency:"Moneda",reference:"Referencia / Nota",saveOperation:"Guardar operación",historyTitle:"Historial de transacciones",historySub:"Fecha, hora, nombre, correo, teléfono, UID, tipo, monto, referencia y estado.",allTransactions:"Todas las transacciones",exchange:"Cambio",ordersSales:"Pedidos / ventas",allPeriods:"Todas las fechas",days7:"7 días",days15:"15 días",days30:"30 días",days90:"90 días",days365:"365 días",allPeople:"Todos los usuarios / vendedores"}
};
function lang(){return $("adminLanguage")?.value||localStorage.getItem("mystroAdminLang")||"ht"}
function t(k){return TX[lang()]?.[k]||TX.ht[k]||k}
function text(sel,key){document.querySelectorAll(sel).forEach(el=>{if(el)el.textContent=t(key)})}
function placeholder(sel,key){document.querySelectorAll(sel).forEach(el=>el.setAttribute("placeholder",t(key)))}
function option(sel,value,key){const el=document.querySelector(sel);if(!el)return;const o=[...el.options].find(x=>x.value===value);if(o)o.textContent=t(key)}
function translate(){
  if(busy)return;busy=true;
  text("#adminBrandText","brand");text("#adminChatTopBtn","message");
  text("#adminUsersManager h2","allUsers");text("#adminUsersManager .panel-sub","usersSub");text("#adminUsersRefresh","refresh");placeholder("#adminUsersSearch","searchUsers");
  text(".products-admin-panel h2","productInfo");text(".products-admin-panel .panel-sub","productSub");
  text("#mwAdmin>h2","approval");text("#mwAdmin>p","approvalSub");text("#mwRefresh","refresh");
  const mwHeads=document.querySelectorAll("#mwAdmin h3");if(mwHeads[0])mwHeads[0].textContent=t("pendingWallet");if(mwHeads[1])mwHeads[1].textContent=t("ordersValidate");
  text("#adminPrivateChat h2","privateChat");text("#adminPrivateChat>p","privateSub");text("#privateOpen","openChat");text("#adminPrivateSend","send");placeholder("#adminPrivateInput","writeAdmin");option("#privateUserSelect","","chooseClient");
  text("#adminManualOps h2","manualTitle");text("#adminManualOps .panel-sub","manualSub");
  const labels=document.querySelectorAll("#adminManualForm label>span");const keys=["user","type","amount","currency","reference"];labels.forEach((el,i)=>{if(keys[i])el.textContent=t(keys[i])});
  text("#adminManualSave","saveOperation");option("#adminManualType","deposit","deposit");option("#adminManualType","withdrawal","withdrawal");
  text("#adminTransactionHistory h2","historyTitle");text("#adminTransactionHistory .panel-sub","historySub");text("#adminHistoryRefresh","refresh");
  option("#adminHistoryFilter","all","allTransactions");option("#adminHistoryFilter","deposit","deposit");option("#adminHistoryFilter","withdrawal","withdrawal");option("#adminHistoryFilter","exchange","exchange");option("#adminHistoryFilter","order","ordersSales");
  option("#adminHistoryPeriod","all","allPeriods");option("#adminHistoryPeriod","7","days7");option("#adminHistoryPeriod","15","days15");option("#adminHistoryPeriod","30","days30");option("#adminHistoryPeriod","90","days90");option("#adminHistoryPeriod","365","days365");option("#adminHistoryUser","all","allPeople");
  document.querySelectorAll("[data-admin-menu-key]").forEach(el=>el.textContent=t(el.dataset.adminMenuKey));
  busy=false;
}
function knownSections(){return [...document.querySelectorAll("#adminDashboard>.hero-card,#adminDashboard>.stats-grid,#adminDashboard>.admin-grid,#adminDashboard>.quick-panel,#adminDashboard>#adminStatus,#mwAdmin,#adminUsersManager,.products-admin-panel,#adminManualOps,#adminTransactionHistory,#adminPrivateChat")]}
function showView(view){currentView=view;const dashboard=$("adminDashboard");if(!dashboard)return;knownSections().forEach(el=>el.hidden=true);
  const show=s=>document.querySelectorAll(s).forEach(el=>el.hidden=false);
  if(view==="dashboard")show("#adminDashboard>.hero-card,#adminDashboard>.stats-grid,#adminDashboard>.admin-grid,#adminDashboard>.quick-panel,#adminDashboard>#adminStatus");
  if(view==="approvals")show("#mwAdmin");if(view==="users")show("#adminUsersManager");if(view==="products")show(".products-admin-panel");if(view==="manual")show("#adminManualOps");if(view==="history")show("#adminTransactionHistory");
  if(view==="chat"){show("#adminPrivateChat");window.MystroAdminChat?.open?.()}
  document.querySelectorAll(".admin-menu-item").forEach(b=>b.classList.toggle("active",b.dataset.view===view));closeMenu();translate();
}
function closeMenu(){const d=$("adminMenuDrawer"),o=$("adminMenuOverlay");d?.classList.remove("open");o?.classList.remove("open")}
function openMenu(){const d=$("adminMenuDrawer"),o=$("adminMenuOverlay");d?.classList.add("open");o?.classList.add("open")}
function menu(){if($("adminMenuDrawer"))return;document.body.insertAdjacentHTML("beforeend",`<div id="adminMenuOverlay" class="admin-menu-overlay"></div><aside id="adminMenuDrawer" class="admin-menu-drawer"><div class="admin-menu-head"><strong>Mystro-Shop</strong><button id="adminMenuClose" type="button">×</button></div>${[["dashboard","dashboard","🏠"],["approvals","approvals","✅"],["users","users","👥"],["products","products","🛍️"],["manual","manual","💰"],["history","history","🕘"],["chat","chat","💬"]].map(([v,k,i])=>`<button class="admin-menu-item" data-view="${v}" type="button"><span>${i}</span><b data-admin-menu-key="${k}">${k}</b></button>`).join("")}</aside>`);$("adminMenuOverlay").onclick=closeMenu;$("adminMenuClose").onclick=closeMenu;document.querySelectorAll(".admin-menu-item").forEach(b=>b.onclick=()=>showView(b.dataset.view));
  const trigger=$("adminMenuBtn")||document.querySelector(".menu-mark");if(trigger)trigger.onclick=e=>{e.preventDefault();e.stopPropagation();openMenu()};translate();
}
function style(){if($("adminUiV3Css"))return;const s=document.createElement("style");s.id="adminUiV3Css";s.textContent=`.admin-menu-trigger{border:0;background:#edf1f6;border-radius:14px;width:46px;height:46px;font-size:24px;color:#14213d}.admin-brand-wrap{display:flex;align-items:center;gap:10px}.admin-menu-overlay{position:fixed;inset:0;background:#10182880;z-index:99990;display:none}.admin-menu-overlay.open{display:block}.admin-menu-drawer{position:fixed;left:0;top:0;bottom:0;width:min(310px,86vw);background:#fff;z-index:99991;padding:18px;transform:translateX(-105%);transition:.22s ease;box-shadow:16px 0 40px #10182826}.admin-menu-drawer.open{transform:translateX(0)}.admin-menu-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:16px;font-size:20px}.admin-menu-head button{border:0;background:#f2f4f7;border-radius:10px;width:40px;height:40px;font-size:24px}.admin-menu-item{width:100%;display:flex;align-items:center;gap:12px;padding:13px;border:0;border-radius:13px;background:#fff;text-align:left;font:inherit;color:#14213d;margin:5px 0}.admin-menu-item:hover,.admin-menu-item.active{background:#eef4ff;color:#2448c8}.admin-menu-item span{font-size:20px}.admin-menu-item b{font-size:15px}.admin-topbar{position:sticky;top:0;z-index:500}.admin-shell{min-height:100vh}`;document.head.appendChild(s)}
function start(){style();menu();$("adminLanguage")?.addEventListener("change",()=>setTimeout(translate,0));const obs=new MutationObserver(()=>{translate();setTimeout(()=>showView(currentView),0)});const d=$("adminDashboard");if(d)obs.observe(d,{childList:true,subtree:true});setTimeout(()=>showView("dashboard"),450);translate()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
