import {getApps,getApp,initializeApp} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import {getAuth,onAuthStateChanged} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import {getFirestore,collection,addDoc,getDocs,getDoc,doc,updateDoc,setDoc,serverTimestamp,query,where,limit,runTransaction} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";

const cfg={apiKey:"AIzaSyC3JebExbgH1n40wzpwNjtASmOPG1tuKIs",authDomain:"mystroshop-eab92.firebaseapp.com",projectId:"mystroshop-eab92",storageBucket:"mystroshop-eab92.firebasestorage.app",messagingSenderId:"104073035061",appId:"1:104073035061:web:59d2779f2db7a8a3be207c"};
const app=getApps().length?getApp():initializeApp(cfg),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const tm=v=>v?.toDate?v.toDate().getTime():v?.seconds?v.seconds*1000:new Date(v||0).getTime()||0;
const money=n=>`G ${(Number(n)||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const PAY={moncash:{label:"MonCash",name:"CASTOR Dieumène",phone:"+509 3676 3122",icon:"💵"},natcash:{label:"NatCash",name:"Luc Jules Michel Castor",phone:"+509 4176 6115",icon:"📱"}};
const ISO="AD AE AF AG AI AL AM AO AQ AR AS AT AU AW AX AZ BA BB BD BE BF BG BH BI BJ BL BM BN BO BQ BR BS BT BV BW BY BZ CA CC CD CF CG CH CI CK CL CM CN CO CR CU CV CW CX CY CZ DE DJ DK DM DO DZ EC EE EG EH ER ES ET FI FJ FK FM FO FR GA GB GD GE GF GG GH GI GL GM GN GP GQ GR GS GT GU GW GY HK HM HN HR HT HU ID IE IL IM IN IO IQ IR IS IT JE JM JO JP KE KG KH KI KM KN KP KR KW KY KZ LA LB LC LI LK LR LS LT LU LV LY MA MC MD ME MF MG MH MK ML MM MN MO MP MQ MR MS MT MU MV MW MX MY MZ NA NC NE NF NG NI NL NO NP NR NU NZ OM PA PE PF PG PH PK PL PM PN PR PS PT PW PY QA RE RO RS RU RW SA SB SC SD SE SG SH SI SJ SK SL SM SN SO SR SS ST SV SX SY SZ TC TD TF TG TH TJ TK TL TM TN TO TR TT TV TW TZ UA UG UM US UY UZ VA VC VE VG VI VN VU WF WS YE YT ZA ZM ZW".split(" ");
const HAITI={
"Artibonite":["Dessalines","Desdunes","Petite-Rivière-de-l'Artibonite","Grande-Saline","Gonaïves","Ennery","L'Estère","Anse-Rouge","Gros-Morne","Terre-Neuve","Marmelade","Saint-Michel-de-l'Attalaye","Les Arcadins","La Chapelle","Liancourt","Saint-Marc","Verrettes"],
"Centre":["Cerca-la-Source","Thomassique","Hinche","Cerca-Carvajal","Maïssade","Thomonde","Lascahobas","Baptiste","Belladère","Savanette","Mirebalais","Boucan-Carré","Saut-d'Eau"],
"Grand'Anse":["Anse-d'Hainault","Dame-Marie","Les Irois","Corail","Beaumont","Pestel","Roseaux","Jérémie","Abricots","Chambellan","Marfranc","Moron","Trou-Bonbon"],
"Nippes":["Miragoâne","Petite-Rivière-de-Nippes","Fonds-des-Nègres","Paillant","Anse-à-Veau","L'Asile","Petit-Trou-de-Nippes","Arnaud","Plaisance-du-Sud","Baradères","Grand-Boucan"],
"Nord":["Acul-du-Nord","Milot","Plaine-du-Nord","Borgne","Port-Margot","Cap-Haïtien","Limonade","Quartier-Morin","Grande-Rivière-du-Nord","Bahon","Limbé","Bas-Limbé","Plaisance","Pilate","Saint-Raphaël","Dondon","Pignon","Ranquitte","La Victoire"],
"Nord-Est":["Fort-Liberté","Ferrier","Perches","Ouanaminthe","Capotille","Mont-Organisé","Trou-du-Nord","Caracol","Grand-Bassin","Sainte-Suzanne","Terrier-Rouge","Vallières","Carice","Mombin-Crochu"],
"Nord-Ouest":["Môle-Saint-Nicolas","Baie-de-Henne","Bombardopolis","Jean-Rabel","Port-de-Paix","Bassin-Bleu","Chansolme","La Tortue","Lapointe","Saint-Louis-du-Nord","Anse-à-Foleur"],
"Ouest":["Arcahaie","Cabaret","Croix-des-Bouquets","Cornillon","Fonds-Verrettes","Ganthier","Thomazeau","Anse-à-Galets","Pointe-à-Raquette","Léogâne","Grand-Goâve","Petit-Goâve","Port-au-Prince","Carrefour","Cité Soleil","Delmas","Gressier","Kenscoff","Pétion-Ville","Tabarre"],
"Sud":["Aquin","Cavaillon","Saint-Louis-du-Sud","Fonds-des-Blancs","Les Cayes","Camp-Perrin","Chantal","Île-à-Vache","Maniche","Torbeck","Chardonnières","Les Anglais","Tiburon","Les Côteaux","Port-à-Piment","Roche-à-Bateau","Port-Salut","Arniquet","Saint-Jean-du-Sud"],
"Sud-Est":["Bainet","Côtes-de-Fer","Belle-Anse","Anse-à-Pitres","Grand-Gosier","Thiotte","Jacmel","Cayes-Jacmel","La Vallée-de-Jacmel","Marigot"]
};
const W={
ht:{method:"Metòd",amount:"Montan HTG",sender:"Nimewo ki voye lajan an",reference:"Referans tranzaksyon",proof:"Foto prèv tranzaksyon",receive:"Nimewo pou resevwa retrè a",send:"Voye demann lan",sending:"Ap voye...",deposit:"Depo manyèl",withdraw:"Retrè manyèl",name:"Non",number:"Nimewo",depositHelp:"Voye lajan an sou kont sa a epi mete foto prèv la. Balans lan chanje sèlman apre admin valide.",withdrawHelp:"Retrè a ap rete an atant jiskaske admin valide li.",minimum:"Minimòm 20 HTG.",needDeposit:"Telefòn, referans ak foto prèv obligatwa.",needPhone:"Mete nimewo retrè a.",sent:"Demann lan voye. Admin dwe valide li.",failed:"Demann lan echwe.",badPhoto:"Chwazi yon foto JPEG, PNG oswa WebP.",bigPhoto:"Foto a twò gwo.",history:"Istwa demann yo",noHistory:"Pa gen demann manyèl.",cantLoad:"Nou pa ka chaje demann yo.",approved:"Apwouve",rejected:"Refize",pending:"An atant",note:"🔐 Depo ak retrè MonCash/NatCash yo fèt manyèlman epi admin sèlman ka apwouve yo.",country:"Peyi",department:"Depatman / Eta / Pwovens",commune:"Komin / Vil",route:"Adrès egzak (ri/route, nimewo kay si genyen)",chooseCountry:"— Chwazi peyi —",chooseDepartment:"— Chwazi depatman —",chooseCommune:"— Chwazi komin —",other:"Lòt / antre manyèlman",requiredAddress:"Pou enskri, ou dwe chwazi peyi, depatman/eta, komin/vil epi antre adrès egzak la.",loading:"Ap chaje...",manualDepartment:"Ekri depatman/eta/pwovens lan",manualCommune:"Ekri komin/vil la",shareLocation:"📍 Pataje pozisyon mwen",stopLocation:"⛔ Sispann pataje pozisyon",locationOn:"Lokalizasyon an aktif pandan Mystro-Shop louvri.",locationOff:"Lokalizasyon an dezaktive.",locationDenied:"Ou pa bay pèmisyon lokalizasyon. Adrès ou rete anrejistre."},
fr:{method:"Méthode",amount:"Montant HTG",sender:"Numéro ayant envoyé l'argent",reference:"Référence de transaction",proof:"Photo de preuve de transaction",receive:"Numéro pour recevoir le retrait",send:"Envoyer la demande",sending:"Envoi...",deposit:"Dépôt manuel",withdraw:"Retrait manuel",name:"Nom",number:"Numéro",depositHelp:"Envoyez l'argent sur ce compte puis joignez la preuve. Le solde change uniquement après validation par l'administrateur.",withdrawHelp:"Le retrait restera en attente jusqu'à validation par l'administrateur.",minimum:"Minimum 20 HTG.",needDeposit:"Téléphone, référence et photo de preuve sont obligatoires.",needPhone:"Saisissez le numéro de retrait.",sent:"Demande envoyée. L'administrateur doit la valider.",failed:"Échec de la demande.",badPhoto:"Choisissez une image JPEG, PNG ou WebP.",bigPhoto:"L'image est trop volumineuse.",history:"Historique des demandes",noHistory:"Aucune demande manuelle.",cantLoad:"Impossible de charger les demandes.",approved:"Approuvé",rejected:"Refusé",pending:"En attente",note:"🔐 Les dépôts et retraits MonCash/NatCash sont manuels et seul l'administrateur peut les valider.",country:"Pays",department:"Département / État / Province",commune:"Commune / Ville",route:"Adresse exacte (rue/route, numéro si disponible)",chooseCountry:"— Choisir le pays —",chooseDepartment:"— Choisir le département —",chooseCommune:"— Choisir la commune —",other:"Autre / saisir manuellement",requiredAddress:"Pour vous inscrire, choisissez le pays, le département/État, la commune/ville et saisissez l'adresse exacte.",loading:"Chargement...",manualDepartment:"Saisissez le département/État/province",manualCommune:"Saisissez la commune/ville",shareLocation:"📍 Partager ma position",stopLocation:"⛔ Arrêter le partage",locationOn:"La localisation est active pendant que Mystro-Shop est ouvert.",locationOff:"La localisation est désactivée.",locationDenied:"Vous n'avez pas autorisé la localisation. Votre adresse déclarée reste enregistrée."},
en:{method:"Method",amount:"Amount HTG",sender:"Number that sent the money",reference:"Transaction reference",proof:"Transaction proof photo",receive:"Number to receive withdrawal",send:"Submit request",sending:"Sending...",deposit:"Manual deposit",withdraw:"Manual withdrawal",name:"Name",number:"Number",depositHelp:"Send the money to this account and attach proof. The balance changes only after admin approval.",withdrawHelp:"The withdrawal will remain pending until admin approval.",minimum:"Minimum 20 HTG.",needDeposit:"Phone, reference and proof photo are required.",needPhone:"Enter the withdrawal phone number.",sent:"Request sent. Admin approval is required.",failed:"Request failed.",badPhoto:"Choose a JPEG, PNG or WebP image.",bigPhoto:"The image is too large.",history:"Request history",noHistory:"No manual requests.",cantLoad:"Unable to load requests.",approved:"Approved",rejected:"Rejected",pending:"Pending",note:"🔐 MonCash/NatCash deposits and withdrawals are manual and only the admin can approve them.",country:"Country",department:"Department / State / Province",commune:"Municipality / City",route:"Exact address (street/road, house number if available)",chooseCountry:"— Choose country —",chooseDepartment:"— Choose state/department —",chooseCommune:"— Choose city —",other:"Other / enter manually",requiredAddress:"To register, choose your country, state/department, city/municipality and enter the exact address.",loading:"Loading...",manualDepartment:"Enter state/department/province",manualCommune:"Enter city/municipality",shareLocation:"📍 Share my location",stopLocation:"⛔ Stop sharing location",locationOn:"Location sharing is active while Mystro-Shop is open.",locationOff:"Location sharing is off.",locationDenied:"Location permission was not granted. Your declared address remains saved."},
es:{method:"Método",amount:"Monto HTG",sender:"Número que envió el dinero",reference:"Referencia de transacción",proof:"Foto de prueba de transacción",receive:"Número para recibir el retiro",send:"Enviar solicitud",sending:"Enviando...",deposit:"Depósito manual",withdraw:"Retiro manual",name:"Nombre",number:"Número",depositHelp:"Envíe el dinero a esta cuenta y adjunte la prueba. El saldo cambia solo después de la aprobación del administrador.",withdrawHelp:"El retiro quedará pendiente hasta la aprobación del administrador.",minimum:"Mínimo 20 HTG.",needDeposit:"Teléfono, referencia y foto de prueba son obligatorios.",needPhone:"Ingrese el número para el retiro.",sent:"Solicitud enviada. Requiere aprobación del administrador.",failed:"La solicitud falló.",badPhoto:"Elija una imagen JPEG, PNG o WebP.",bigPhoto:"La imagen es demasiado grande.",history:"Historial de solicitudes",noHistory:"No hay solicitudes manuales.",cantLoad:"No se pueden cargar las solicitudes.",approved:"Aprobado",rejected:"Rechazado",pending:"Pendiente",note:"🔐 Los depósitos y retiros MonCash/NatCash son manuales y solo el administrador puede aprobarlos.",country:"País",department:"Departamento / Estado / Provincia",commune:"Municipio / Ciudad",route:"Dirección exacta (calle/ruta y número si existe)",chooseCountry:"— Elegir país —",chooseDepartment:"— Elegir departamento —",chooseCommune:"— Elegir municipio —",other:"Otro / escribir manualmente",requiredAddress:"Para registrarse, elija país, departamento/estado, municipio/ciudad e ingrese la dirección exacta.",loading:"Cargando...",manualDepartment:"Escriba departamento/estado/provincia",manualCommune:"Escriba municipio/ciudad",shareLocation:"📍 Compartir mi ubicación",stopLocation:"⛔ Dejar de compartir ubicación",locationOn:"La ubicación está activa mientras Mystro-Shop esté abierto.",locationOff:"La ubicación está desactivada.",locationDenied:"No autorizó la ubicación. Su dirección declarada permanece guardada."}
};
let user=null,profile={},mode="deposit",provider="moncash",geoWatch=null,lastGeoSave=0;

function lang(){const x=$("languageSelector")?.value||$("adminLanguage")?.value||localStorage.getItem("mystroLanguage")||localStorage.getItem("mystroAdminLang")||"ht";return W[x]?x:"ht"}
function tr(k){return W[lang()]?.[k]||W.ht[k]||k}
function css(){if($("mwcss"))return;const s=document.createElement("style");s.id="mwcss";s.textContent=`
.mw-note{margin:14px 0;padding:13px;border-radius:14px;background:#eef4ff;border:1px solid #d8e4ff;color:#2643a2;line-height:1.45}.mw-list{display:grid;gap:9px}.mw-row{display:grid;gap:5px;padding:12px;border:1px solid #e5e7eb;border-radius:13px;background:#fff}.mw-pill{width:max-content;padding:4px 8px;border-radius:999px;font-size:12px;font-weight:800;background:#fff7ed;color:#9a3412}.mw-pill.approved{background:#ecfdf3;color:#166534}.mw-pill.rejected{background:#fff1f2;color:#9f1239}.mw-modal{position:fixed;inset:0;display:none;align-items:center;justify-content:center;padding:18px;background:#0f172ab8;z-index:1000000}.mw-modal.open{display:flex}.mw-card{position:relative;width:min(470px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:22px;padding:22px}.mw-close{position:absolute;right:12px;top:8px;border:0;background:none;font-size:28px}.mw-field{display:grid;gap:6px;margin:12px 0}.mw-field input,.mw-field select{padding:12px;border:1px solid #d0d5dd;border-radius:12px;font:inherit}.mw-rec{padding:13px;border-radius:13px;background:#f8faff;border:1px solid #dbe4ff;line-height:1.55}.mw-btn{width:100%;border:0;border-radius:12px;padding:12px;background:#3159db;color:#fff;font-weight:800}.mw-admin{margin-top:16px;background:#fff;border-radius:18px;padding:18px;box-shadow:0 7px 24px #1018280f}.mw-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.mw-a{padding:12px;border:1px solid #e5e7eb;border-radius:13px;margin:9px 0}.mw-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.mw-actions button{border:0;border-radius:9px;padding:8px 10px;font-weight:800}.ok{background:#dcfae6;color:#067647}.no{background:#fee4e2;color:#b42318}.proof{background:#eef2ff;color:#3448b6}.geo-extra{display:grid;gap:10px;margin-top:10px}.geo-extra label{display:grid;gap:6px}.geo-extra select,.geo-extra input{width:100%;padding:12px;border:1px solid #d0d5dd;border-radius:12px;font:inherit}.geo-manual[hidden]{display:none}.location-share{margin-top:12px;width:100%}.location-status{display:block;margin-top:8px;color:#667085}@media(max-width:760px){.mw-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}

function modal(){
 if($("mwModal"))return;
 document.body.insertAdjacentHTML("beforeend",`<div id="mwModal" class="mw-modal"><div class="mw-card"><button id="mwClose" class="mw-close">×</button><h2 id="mwTitle"></h2><div id="mwRec" class="mw-rec"></div><label class="mw-field"><span id="mwMethodLabel"></span><select id="mwProvider"><option value="moncash">MonCash</option><option value="natcash">NatCash</option></select></label><label class="mw-field"><span id="mwAmountLabel"></span><input id="mwAmount" type="number" min="20" step="1"></label><div id="mwDep"><label class="mw-field"><span id="mwSenderLabel"></span><input id="mwSender" type="tel"></label><label class="mw-field"><span id="mwRefLabel"></span><input id="mwRef"></label><label class="mw-field"><span id="mwProofLabel"></span><input id="mwProof" type="file" accept="image/jpeg,image/png,image/webp"></label></div><div id="mwWith" hidden><label class="mw-field"><span id="mwPhoneLabel"></span><input id="mwPhone" type="tel"></label></div><button id="mwSubmit" class="mw-btn"></button></div></div><div id="mwProofModal" class="mw-modal"><div class="mw-card"><button id="mwProofClose" class="mw-close">×</button><h2 id="mwProofTitle"></h2><img id="mwProofImg" style="max-width:100%;border-radius:12px"></div></div>`);
 $("mwClose").onclick=()=>$("mwModal").classList.remove("open");$("mwProofClose").onclick=()=>$("mwProofModal").classList.remove("open");$("mwProvider").onchange=e=>{provider=e.target.value;paint()};$("mwSubmit").onclick=submit;translateWallet()
}
function translateWallet(){if(!$("mwModal"))return;$("mwMethodLabel").textContent=tr("method");$("mwAmountLabel").textContent=tr("amount");$("mwSenderLabel").textContent=tr("sender");$("mwRefLabel").textContent=tr("reference");$("mwProofLabel").textContent=tr("proof");$("mwPhoneLabel").textContent=tr("receive");$("mwSubmit").textContent=tr("send");$("mwProofTitle").textContent=tr("proof");const n=$("mwHistoryNote");if(n)n.textContent=tr("note");const h=$("mwHistoryTitle");if(h)h.textContent=tr("history");paint();history()}
function paint(){if(!$("mwTitle"))return;const d=mode==="deposit",p=PAY[provider];$("mwTitle").textContent=`${d?"⬇️":"⬆️"} ${tr(d?"deposit":"withdraw")} ${p.label}`;$("mwDep").hidden=!d;$("mwWith").hidden=d;$("mwRec").hidden=!d;$("mwRec").innerHTML=d?`${p.icon} <strong>${esc(p.label)}</strong><br><b>${esc(tr("name"))}:</b> ${esc(p.name)}<br><b>${esc(tr("number"))}:</b> ${esc(p.phone)}<br><small>${esc(tr("depositHelp"))}</small>`:`<b>${esc(tr("withdrawHelp"))}</b>`}
function open(m,p){if(!user)return;mode=m;provider=p;$("mwProvider").value=p;["mwAmount","mwSender","mwRef","mwPhone"].forEach(id=>$(id).value="");$("mwProof").value="";paint();$("mwModal").classList.add("open")}
async function image64(file){if(!file||!["image/jpeg","image/png","image/webp"].includes(file.type))throw Error(tr("badPhoto"));if(file.size>6e6)throw Error(tr("bigPhoto"));const src=await new Promise((r,j)=>{const f=new FileReader();f.onload=()=>r(f.result);f.onerror=j;f.readAsDataURL(file)});const im=await new Promise((r,j)=>{const x=new Image();x.onload=()=>r(x);x.onerror=j;x.src=src});const z=Math.min(1,900/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=Math.max(1,Math.round(im.width*z));c.height=Math.max(1,Math.round(im.height*z));c.getContext("2d").drawImage(im,0,0,c.width,c.height);let out=c.toDataURL("image/jpeg",.65);if(out.length>850000)out=c.toDataURL("image/jpeg",.48);if(out.length>890000)throw Error(tr("bigPhoto"));return out}
async function submit(){const amount=Number($("mwAmount").value);if(!amount||amount<20)return alert(tr("minimum"));const b=$("mwSubmit"),old=b.textContent;b.disabled=true;b.textContent=tr("sending");try{const data={userId:user.uid,userName:profile.name||user.email||"Client",userEmail:user.email||"",type:mode,provider,amount,currency:"HTG",status:"pending",createdAt:serverTimestamp()};if(mode==="deposit"){data.senderPhone=$("mwSender").value.trim();data.reference=$("mwRef").value.trim();const f=$("mwProof").files?.[0];if(!data.senderPhone||!data.reference||!f)throw Error(tr("needDeposit"));data.proofDataUrl=await image64(f)}else{data.phone=$("mwPhone").value.trim();if(!data.phone)throw Error(tr("needPhone"))}await addDoc(collection(db,"manualTransactions"),data);$("mwModal").classList.remove("open");await history();alert(tr("sent"))}catch(e){console.error(e);alert(e.message||tr("failed"))}finally{b.disabled=false;b.textContent=old}}
async function history(){const box=$("mwHistoryList");if(!box||!user)return;try{const s=await getDocs(query(collection(db,"manualTransactions"),where("userId","==",user.uid),limit(80))),a=s.docs.map(d=>({id:d.id,...d.data()})).sort((x,y)=>tm(y.createdAt)-tm(x.createdAt)),lab=x=>x==="approved"?tr("approved"):x==="rejected"?tr("rejected"):tr("pending");box.innerHTML=a.length?a.map(x=>`<div class="mw-row"><b>${x.type==="deposit"?"⬇️ "+tr("deposit"):"⬆️ "+tr("withdraw")} · ${esc((x.provider||"").toUpperCase())}</b><span>${money(x.amount)}</span><span class="mw-pill ${esc(x.status||"pending")}">${lab(x.status)}</span><small>${esc(x.reference||x.phone||"")}</small></div>`).join(""):esc(tr("noHistory"))}catch(e){box.textContent=tr("cantLoad")}}

function countryNames(){const display=new Intl.DisplayNames([lang()==="ht"?"fr":lang()],{type:"region"}),english=new Intl.DisplayNames(["en"],{type:"region"});return ISO.map(code=>({code,name:english.of(code)||code,label:display.of(code)||english.of(code)||code})).sort((a,b)=>a.label.localeCompare(b.label))}
function fillCountry(){const s=$("authCountry");if(!s||s.tagName!=="SELECT")return;const current=s.value;s.innerHTML=`<option value="">${esc(tr("chooseCountry"))}</option>`+countryNames().map(c=>`<option value="${esc(c.name)}" data-code="${c.code}">${esc(c.label)}</option>`).join("");if(current&&[...s.options].some(o=>o.value===current))s.value=current}
function fillSelect(sel,items,placeholder){sel.innerHTML=`<option value="">${esc(placeholder)}</option>`+items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("")+`<option value="__manual__">${esc(tr("other"))}</option>`}
function showManual(type,on){const i=$(type==="department"?"authDepartmentManual":"authCommuneManual");if(!i)return;i.hidden=!on;i.disabled=!on;i.required=on&&$("authModal")?.dataset.mode==="register";i.placeholder=tr(type==="department"?"manualDepartment":"manualCommune");if(!on)i.value=""}
async function loadRegions(){const c=$("authCountry"),d=$("authDepartment"),m=$("authCommune");if(!c||!d||!m)return;showManual("department",false);showManual("commune",false);fillSelect(m,[],tr("chooseCommune"));const code=c.selectedOptions[0]?.dataset.code||"";if(!c.value){fillSelect(d,[],tr("chooseDepartment"));return}d.innerHTML=`<option value="">${esc(tr("loading"))}</option>`;if(code==="HT"){fillSelect(d,Object.keys(HAITI),tr("chooseDepartment"));return}try{const r=await fetch("https://countriesnow.space/api/v0.1/countries/states",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({country:c.value})}),j=await r.json(),states=(j?.data?.states||[]).map(x=>x.name).filter(Boolean);fillSelect(d,states,tr("chooseDepartment"))}catch{fillSelect(d,[],tr("chooseDepartment"))}}
async function loadCommunes(){const c=$("authCountry"),d=$("authDepartment"),m=$("authCommune");if(!c||!d||!m)return;showManual("commune",false);const code=c.selectedOptions[0]?.dataset.code||"";if(!d.value||d.value==="__manual__"){fillSelect(m,[],tr("chooseCommune"));return}m.innerHTML=`<option value="">${esc(tr("loading"))}</option>`;if(code==="HT"){fillSelect(m,HAITI[d.value]||[],tr("chooseCommune"));return}try{const r=await fetch("https://countriesnow.space/api/v0.1/countries/state/cities",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({country:c.value,state:d.value})}),j=await r.json(),cities=Array.isArray(j?.data)?j.data.filter(Boolean):[];fillSelect(m,cities,tr("chooseCommune"))}catch{fillSelect(m,[],tr("chooseCommune"))}}
function regValue(type){const s=$(type==="department"?"authDepartment":"authCommune");if(!s)return"";if(s.value==="__manual__")return $(type==="department"?"authDepartmentManual":"authCommuneManual")?.value.trim()||"";return s.value.trim()}
function syncRegFields(){const reg=$("authModal")?.dataset.mode==="register";["authDepartment","authCommune","authAddressRoute"].forEach(id=>{const e=$(id);if(e){e.disabled=!reg;e.required=reg}});["department","commune"].forEach(type=>{const s=$(type==="department"?"authDepartment":"authCommune"),i=$(type==="department"?"authDepartmentManual":"authCommuneManual");if(i){const on=reg&&s?.value==="__manual__";i.disabled=!on;i.required=on;i.hidden=!on}})}
function setupRegistrationAddress(){
 const box=$("authRegisterFields"),old=$("authCountry"),form=$("authForm");if(!box||!old||!form||$("authDepartment"))return;
 const label=old.closest("label");label.innerHTML=`<span data-i18n="country">${esc(tr("country"))}</span><select id="authCountry" autocomplete="country-name"></select>`;
 label.insertAdjacentHTML("afterend",`<div id="geoRegistrationFields" class="geo-extra"><label><span id="geoDepartmentLabel"></span><select id="authDepartment"></select><input id="authDepartmentManual" class="geo-manual" hidden></label><label><span id="geoCommuneLabel"></span><select id="authCommune"></select><input id="authCommuneManual" class="geo-manual" hidden></label><label><span id="geoRouteLabel"></span><input id="authAddressRoute" autocomplete="street-address" maxlength="240"></label></div>`);
 const c=$("authCountry"),d=$("authDepartment"),m=$("authCommune");fillCountry();fillSelect(d,[],tr("chooseDepartment"));fillSelect(m,[],tr("chooseCommune"));
 c.addEventListener("change",loadRegions);d.addEventListener("change",()=>{showManual("department",d.value==="__manual__");loadCommunes();syncRegFields()});m.addEventListener("change",()=>{showManual("commune",m.value==="__manual__");syncRegFields()});
 form.addEventListener("submit",e=>{if($("authModal")?.dataset.mode!=="register")return;const country=c.value.trim(),department=regValue("department"),commune=regValue("commune"),address=$("authAddressRoute").value.trim();if(!country||!department||!commune||address.length<3){e.preventDefault();e.stopImmediatePropagation();alert(tr("requiredAddress"));return}sessionStorage.setItem("mystroPendingAddress",JSON.stringify({country,countryCode:c.selectedOptions[0]?.dataset.code||"",department,commune,address,addressRoute:address,registeredAddressAt:Date.now()}))},true);
 new MutationObserver(syncRegFields).observe($("authModal"),{attributes:true,attributeFilter:["data-mode"]});syncRegFields();translateRegistration()
}
function translateRegistration(){if(!$("authDepartment"))return;$("geoDepartmentLabel").textContent=tr("department");$("geoCommuneLabel").textContent=tr("commune");$("geoRouteLabel").textContent=tr("route");const dep=$("authDepartment"),com=$("authCommune");const dv=dep.value,cv=com.value;fillCountry();if($("authCountry").selectedOptions[0]?.dataset.code==="HT"){fillSelect(dep,Object.keys(HAITI),tr("chooseDepartment"));dep.value=[...dep.options].some(o=>o.value===dv)?dv:"";if(dep.value)fillSelect(com,HAITI[dep.value]||[],tr("chooseCommune"));else fillSelect(com,[],tr("chooseCommune"));com.value=[...com.options].some(o=>o.value===cv)?cv:""}else{if(dep.options[0])dep.options[0].textContent=tr("chooseDepartment");if(com.options[0])com.options[0].textContent=tr("chooseCommune")}showManual("department",dep.value==="__manual__");showManual("commune",com.value==="__manual__");syncRegFields()}
async function savePendingAddress(u){let raw=sessionStorage.getItem("mystroPendingAddress");if(!raw||!u)return;let data;try{data=JSON.parse(raw)}catch{return}for(let i=0;i<8;i++){try{const ref=doc(db,"users",u.uid),s=await getDoc(ref);if(s.exists()){await updateDoc(ref,{country:data.country||"",countryCode:data.countryCode||"",department:data.department||"",commune:data.commune||"",address:data.address||"",addressRoute:data.addressRoute||"",addressVerifiedAt:serverTimestamp()});sessionStorage.removeItem("mystroPendingAddress");return}}catch{}await new Promise(r=>setTimeout(r,350+250*i))}}

async function savePosition(pos){if(!user||Date.now()-lastGeoSave<15000)return;lastGeoSave=Date.now();const c=pos.coords;try{await updateDoc(doc(db,"users",user.uid),{geo:{lat:Number(c.latitude),lng:Number(c.longitude),accuracy:Number(c.accuracy||0)},locationSharing:true,locationUpdatedAt:serverTimestamp(),lastSeen:serverTimestamp()});const s=$("locationShareStatus");if(s)s.textContent=tr("locationOn")}catch(e){console.warn("location",e)}}
function startGeo(){if(!navigator.geolocation||geoWatch!==null||!user)return;geoWatch=navigator.geolocation.watchPosition(savePosition,()=>{const s=$("locationShareStatus");if(s)s.textContent=tr("locationDenied")},{enableHighAccuracy:true,maximumAge:30000,timeout:15000});localStorage.setItem("mystroLocationSharing","1");updateGeoButton()}
async function stopGeo(){if(geoWatch!==null&&navigator.geolocation)navigator.geolocation.clearWatch(geoWatch);geoWatch=null;localStorage.setItem("mystroLocationSharing","0");if(user)try{await updateDoc(doc(db,"users",user.uid),{locationSharing:false,locationStoppedAt:serverTimestamp()})}catch{}updateGeoButton();const s=$("locationShareStatus");if(s)s.textContent=tr("locationOff")}
function updateGeoButton(){const b=$("shareLocationBtn");if(b)b.textContent=localStorage.getItem("mystroLocationSharing")==="1"?tr("stopLocation"):tr("shareLocation")}
function setupLocationSharing(){const card=document.querySelector("#profilePage .profile-card");if(!card||$("shareLocationBtn"))return;card.insertAdjacentHTML("beforeend",`<button id="shareLocationBtn" class="secondary location-share" type="button"></button><small id="locationShareStatus" class="location-status"></small>`);$("shareLocationBtn").onclick=()=>localStorage.getItem("mystroLocationSharing")==="1"?stopGeo():startGeo();updateGeoButton()}

function client(){
 const w=$("walletPage");if(!w)return;css();modal();setupRegistrationAddress();setupLocationSharing();
 if(!$("mwHistory"))w.insertAdjacentHTML("beforeend",`<div id="mwHistoryNote" class="mw-note"></div><div id="mwHistory"><h3 id="mwHistoryTitle"></h3><div id="mwHistoryList" class="mw-list"></div></div>`);
 document.addEventListener("click",e=>{const b=e.target.closest?.("#moncashDepositBtn,#natcashDepositBtn,#moncashWithdrawBtn,#natcashWithdrawBtn");if(!b)return;e.preventDefault();e.stopImmediatePropagation();open(b.id.includes("Withdraw")?"withdrawal":"deposit",b.id.startsWith("natcash")?"natcash":"moncash")},true);
 $("languageSelector")?.addEventListener("change",()=>setTimeout(()=>{translateWallet();translateRegistration();updateGeoButton()},0));
 onAuthStateChanged(auth,async u=>{user=u;if(!u){if(geoWatch!==null)stopGeo();return}try{const s=await getDoc(doc(db,"users",u.uid));profile=s.exists()?s.data():{}}catch{}savePendingAddress(u);history();if(localStorage.getItem("mystroLocationSharing")==="1")startGeo()});
 if(location.hash==="#wallet")setTimeout(()=>document.querySelector('[data-page="wallet"]')?.click(),250);translateWallet()
}
function checkout(){if(!$("payWallet")||$("walletPage"))return;css();$("topupAmount")?.closest(".card")?.insertAdjacentHTML("afterbegin",`<div class="mw-note">${esc(tr("note"))}</div>`);document.addEventListener("click",e=>{if(!e.target.closest?.("#topupMoncash,#topupNatcash,#verifyTopup"))return;e.preventDefault();e.stopImmediatePropagation();location.href="./index.html#wallet"},true)}

async function adminOK(){const u=auth.currentUser;if(!u)return false;const s=await getDoc(doc(db,"users",u.uid));return s.exists()&&String(s.data().role||"").toLowerCase()==="admin"}
function adminUI(){const d=$("adminDashboard");if(!d||$("mwAdmin"))return;css();modal();d.insertAdjacentHTML("afterbegin",`<section id="mwAdmin" class="mw-admin"><h2>✅ Apwobasyon Admin</h2><p>Se sèlman admin ki ka valide/refize kòmand, depo ak retrè.</p><button id="mwRefresh" class="ghost">Rafrechi</button><div class="mw-grid"><div><h3>Depo / retrè an atant</h3><div id="mwAdminTx"></div></div><div><h3>Kòmand pou valide</h3><div id="mwAdminOrders"></div></div></div></section>`);$("mwRefresh").onclick=loadAdmin;document.addEventListener("click",actions);$("adminLanguage")?.addEventListener("change",()=>setTimeout(translateWallet,0));onAuthStateChanged(auth,u=>{if(u)setTimeout(loadAdmin,300)})}
async function loadAdmin(){if(!(await adminOK()))return;const [ts,os]=await Promise.all([getDocs(query(collection(db,"manualTransactions"),limit(250))),getDocs(query(collection(db,"orders"),limit(350)))]),ta=ts.docs.map(d=>({id:d.id,...d.data()})).filter(x=>(x.status||"pending")==="pending"),oa=os.docs.map(d=>({id:d.id,...d.data()})).filter(x=>!["completed","rejected"].includes(String(x.status||"").toLowerCase()));$("mwAdminTx").innerHTML=ta.length?ta.map(x=>`<div class="mw-a"><b>${x.type==="deposit"?"⬇️ Depo":"⬆️ Retrè"} ${esc((x.provider||"").toUpperCase())}</b><p>${esc(x.userName||x.userEmail||x.userId)} · ${money(x.amount)}</p><p>${x.type==="deposit"?`Soti: ${esc(x.senderPhone||"—")} · Ref: ${esc(x.reference||"—")}`:`Pou: ${esc(x.phone||"—")}`}</p><div class="mw-actions">${x.proofDataUrl?`<button class="proof" data-proof="${esc(x.id)}">Gade prèv</button>`:""}<button class="ok" data-ta="${esc(x.id)}">Apwouve</button><button class="no" data-tr="${esc(x.id)}">Refize</button></div></div>`).join(""):"Pa gen demann.";window.__mwproof=Object.fromEntries(ta.map(x=>[x.id,x.proofDataUrl||""]));$("mwAdminOrders").innerHTML=oa.length?oa.map(o=>`<div class="mw-a"><b>📦 ${esc(o.id)}</b><p>${esc(o.buyerName||o.buyerEmail||o.buyerId||"Client")}</p><p>${esc(o.status||"pending")} · ${esc(o.currency||"HTG")} ${(Number(o.total)||0).toLocaleString()}</p><div class="mw-actions"><button class="ok" data-oa="${esc(o.id)}">Apwouve</button><button class="no" data-or="${esc(o.id)}">Refize</button></div></div>`).join(""):"Pa gen kòmand."}
async function actions(e){const p=e.target.closest?.("[data-proof]");if(p){const src=window.__mwproof?.[p.dataset.proof];if(src){$("mwProofImg").src=src;$("mwProofModal").classList.add("open")}return}const a=e.target.closest?.("[data-ta]"),r=e.target.closest?.("[data-tr]"),oa=e.target.closest?.("[data-oa]"),or=e.target.closest?.("[data-or]");try{if(a)await approveTx(a.dataset.ta);else if(r)await updateDoc(doc(db,"manualTransactions",r.dataset.tr),{status:"rejected",rejectedAt:serverTimestamp(),rejectedBy:auth.currentUser.uid});else if(oa)await updateDoc(doc(db,"orders",oa.dataset.oa),{status:"completed",adminApproval:"approved",approvedAt:serverTimestamp(),approvedBy:auth.currentUser.uid});else if(or)await updateDoc(doc(db,"orders",or.dataset.or),{status:"rejected",adminApproval:"rejected",rejectedAt:serverTimestamp(),rejectedBy:auth.currentUser.uid});else return;await loadAdmin()}catch(x){console.error(x);alert(x.message||"Aksyon an echwe.")}}
async function approveTx(id){if(!(await adminOK()))throw Error("Aksè admin obligatwa.");const ref=doc(db,"manualTransactions",id);await runTransaction(db,async t=>{const s=await t.get(ref);if(!s.exists())throw Error("Demann lan pa egziste.");const x=s.data();if(x.status!=="pending")throw Error("Demann deja trete.");const ur=doc(db,"users",x.userId),us=await t.get(ur);if(!us.exists())throw Error("Kliyan pa egziste.");const u=us.data(),cur=Number(u.balances?.HTG??u.balance??0),amt=Number(x.amount)||0;if(x.type==="withdrawal"&&cur<amt)throw Error("Balans kliyan an pa sifi.");const next=x.type==="deposit"?cur+amt:cur-amt;t.update(ur,{"balances.HTG":next,balance:next});t.update(ref,{status:"approved",approvedAt:serverTimestamp(),approvedBy:auth.currentUser.uid})})}

function start(){if($("adminDashboard"))adminUI();else if($("walletPage"))client();checkout()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
