import {getApps,getApp,initializeApp} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import {getAuth,onAuthStateChanged} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import {getFirestore,collection,addDoc,getDocs,getDoc,doc,updateDoc,serverTimestamp,query,where,limit,runTransaction} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";

const cfg={apiKey:"AIzaSyC3JebExbgH1n40wzpwNjtASmOPG1tuKIs",authDomain:"mystroshop-eab92.firebaseapp.com",projectId:"mystroshop-eab92",storageBucket:"mystroshop-eab92.firebasestorage.app",messagingSenderId:"104073035061",appId:"1:104073035061:web:59d2779f2db7a8a3be207c"};
const app=getApps().length?getApp():initializeApp(cfg),auth=getAuth(app),db=getFirestore(app),$=id=>document.getElementById(id);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const tm=v=>v?.toDate?v.toDate().getTime():v?.seconds?v.seconds*1000:new Date(v||0).getTime()||0;
const money=n=>`G ${(Number(n)||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const PAY={
  moncash:{label:"MonCash",name:"CASTOR Dieumène",phone:"+509 3676 3122",icon:"💵"},
  natcash:{label:"NatCash",name:"Luc Jules Michel Castor",phone:"+509 4176 6115",icon:"📱"}
};
let user=null,profile={},mode="deposit",provider="moncash";

function css(){
 if($("mwcss"))return;const s=document.createElement("style");s.id="mwcss";s.textContent=`
 .mw-note{margin:14px 0;padding:13px;border-radius:14px;background:#eef4ff;border:1px solid #d8e4ff;color:#2643a2;line-height:1.45}
 .mw-list{display:grid;gap:9px}.mw-row{display:grid;gap:5px;padding:12px;border:1px solid #e5e7eb;border-radius:13px;background:#fff}
 .mw-pill{width:max-content;padding:4px 8px;border-radius:999px;font-size:12px;font-weight:800;background:#fff7ed;color:#9a3412}.mw-pill.approved{background:#ecfdf3;color:#166534}.mw-pill.rejected{background:#fff1f2;color:#9f1239}
 .mw-modal{position:fixed;inset:0;display:none;align-items:center;justify-content:center;padding:18px;background:#0f172ab8;z-index:1000000}.mw-modal.open{display:flex}
 .mw-card{position:relative;width:min(470px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:22px;padding:22px}.mw-close{position:absolute;right:12px;top:8px;border:0;background:none;font-size:28px}
 .mw-field{display:grid;gap:6px;margin:12px 0}.mw-field input,.mw-field select{padding:12px;border:1px solid #d0d5dd;border-radius:12px;font:inherit}.mw-rec{padding:13px;border-radius:13px;background:#f8faff;border:1px solid #dbe4ff;line-height:1.55}
 .mw-btn{width:100%;border:0;border-radius:12px;padding:12px;background:#3159db;color:#fff;font-weight:800}.mw-admin{margin-top:16px;background:#fff;border-radius:18px;padding:18px;box-shadow:0 7px 24px #1018280f}
 .mw-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.mw-a{padding:12px;border:1px solid #e5e7eb;border-radius:13px;margin:9px 0}.mw-actions{display:flex;gap:8px;flex-wrap:wrap;margin-top:8px}.mw-actions button{border:0;border-radius:9px;padding:8px 10px;font-weight:800}.ok{background:#dcfae6;color:#067647}.no{background:#fee4e2;color:#b42318}.proof{background:#eef2ff;color:#3448b6}
 @media(max-width:760px){.mw-grid{grid-template-columns:1fr}}`;document.head.appendChild(s);
}
function modal(){
 if($("mwModal"))return;document.body.insertAdjacentHTML("beforeend",`<div id="mwModal" class="mw-modal"><div class="mw-card"><button id="mwClose" class="mw-close">×</button><h2 id="mwTitle"></h2><div id="mwRec" class="mw-rec"></div><label class="mw-field">Metòd<select id="mwProvider"><option value="moncash">MonCash</option><option value="natcash">NatCash</option></select></label><label class="mw-field">Montan HTG<input id="mwAmount" type="number" min="20" step="1"></label><div id="mwDep"><label class="mw-field">Nimewo ki voye lajan an<input id="mwSender" type="tel"></label><label class="mw-field">Referans tranzaksyon<input id="mwRef"></label><label class="mw-field">Foto prèv tranzaksyon<input id="mwProof" type="file" accept="image/jpeg,image/png,image/webp"></label></div><div id="mwWith" hidden><label class="mw-field">Nimewo pou resevwa retrè a<input id="mwPhone" type="tel"></label></div><button id="mwSubmit" class="mw-btn">Voye demann lan</button></div></div><div id="mwProofModal" class="mw-modal"><div class="mw-card"><button id="mwProofClose" class="mw-close">×</button><h2>Prèv tranzaksyon</h2><img id="mwProofImg" style="max-width:100%;border-radius:12px"></div></div>`);
 $("mwClose").onclick=()=>$("mwModal").classList.remove("open");$("mwProofClose").onclick=()=>$("mwProofModal").classList.remove("open");$("mwProvider").onchange=e=>{provider=e.target.value;paint()};$("mwSubmit").onclick=submit;
}
function paint(){const d=mode==="deposit",p=PAY[provider];$("mwTitle").textContent=d?`⬇️ Depo manyèl ${p.label}`:`⬆️ Retrè manyèl ${p.label}`;$("mwDep").hidden=!d;$("mwWith").hidden=d;$("mwRec").hidden=!d;$("mwRec").innerHTML=d?`${p.icon} <strong>${esc(p.label)}</strong><br><b>Non:</b> ${esc(p.name)}<br><b>Nimewo:</b> ${esc(p.phone)}<br><small>Voye lajan an sou kont sa a epi mete foto prèv la. Balans lan chanje sèlman apre admin valide.</small>`:"<b>Retrè a ap rete an atant jiskaske admin valide li.</b>"}
function open(m,p){if(!user)return;mode=m;provider=p;$("mwProvider").value=p;["mwAmount","mwSender","mwRef","mwPhone"].forEach(id=>$(id).value="");$("mwProof").value="";paint();$("mwModal").classList.add("open")}
async function image64(file){if(!file||!["image/jpeg","image/png","image/webp"].includes(file.type))throw Error("Chwazi yon foto JPEG, PNG oswa WebP.");if(file.size>6e6)throw Error("Foto a twò gwo.");const src=await new Promise((r,j)=>{const f=new FileReader();f.onload=()=>r(f.result);f.onerror=j;f.readAsDataURL(file)});const im=await new Promise((r,j)=>{const x=new Image();x.onload=()=>r(x);x.onerror=j;x.src=src});const z=Math.min(1,900/Math.max(im.width,im.height)),c=document.createElement("canvas");c.width=Math.max(1,Math.round(im.width*z));c.height=Math.max(1,Math.round(im.height*z));c.getContext("2d").drawImage(im,0,0,c.width,c.height);let out=c.toDataURL("image/jpeg",.65);if(out.length>850000)out=c.toDataURL("image/jpeg",.48);if(out.length>890000)throw Error("Foto a toujou twò gwo.");return out}
async function submit(){const amount=Number($("mwAmount").value);if(!amount||amount<20)return alert("Minimòm 20 HTG.");const b=$("mwSubmit"),old=b.textContent;b.disabled=true;b.textContent="Ap voye...";try{const data={userId:user.uid,userName:profile.name||user.email||"Client",userEmail:user.email||"",type:mode,provider,amount,currency:"HTG",status:"pending",createdAt:serverTimestamp()};if(mode==="deposit"){data.senderPhone=$("mwSender").value.trim();data.reference=$("mwRef").value.trim();const f=$("mwProof").files?.[0];if(!data.senderPhone||!data.reference||!f)throw Error("Telefòn, referans ak foto prèv obligatwa.");data.proofDataUrl=await image64(f)}else{data.phone=$("mwPhone").value.trim();if(!data.phone)throw Error("Mete nimewo retrè a.")}await addDoc(collection(db,"manualTransactions"),data);$("mwModal").classList.remove("open");await history();alert("Demann lan voye. Admin dwe valide li.")}catch(e){console.error(e);alert(e.message||"Demann lan echwe.")}finally{b.disabled=false;b.textContent=old}}
async function history(){const box=$("mwHistoryList");if(!box||!user)return;try{const s=await getDocs(query(collection(db,"manualTransactions"),where("userId","==",user.uid),limit(80))),a=s.docs.map(d=>({id:d.id,...d.data()})).sort((x,y)=>tm(y.createdAt)-tm(x.createdAt)),lab=x=>x==="approved"?"Apwouve":x==="rejected"?"Refize":"An atant";box.innerHTML=a.length?a.map(x=>`<div class="mw-row"><b>${x.type==="deposit"?"⬇️ Depo":"⬆️ Retrè"} · ${esc((x.provider||"").toUpperCase())}</b><span>${money(x.amount)}</span><span class="mw-pill ${esc(x.status||"pending")}">${lab(x.status)}</span><small>${esc(x.reference||x.phone||"")}</small></div>`).join(""):"Pa gen demann manyèl. "}catch(e){box.textContent="Nou pa ka chaje demann yo."}}
function client(){const w=$("walletPage");if(!w)return;css();modal();if(!$("mwHistory"))w.insertAdjacentHTML("beforeend",`<div class="mw-note">🔐 Depo ak retrè MonCash/NatCash yo fèt manyèlman epi <b>admin sèlman</b> ka apwouve yo.</div><div id="mwHistory"><h3>Istwa demann yo</h3><div id="mwHistoryList" class="mw-list"></div></div>`);document.addEventListener("click",e=>{const b=e.target.closest?.("#moncashDepositBtn,#natcashDepositBtn,#moncashWithdrawBtn,#natcashWithdrawBtn");if(!b)return;e.preventDefault();e.stopImmediatePropagation();open(b.id.includes("Withdraw")?"withdrawal":"deposit",b.id.startsWith("natcash")?"natcash":"moncash")},true);onAuthStateChanged(auth,async u=>{user=u;if(!u)return;try{const s=await getDoc(doc(db,"users",u.uid));profile=s.exists()?s.data():{}}catch{}history()});if(location.hash==="#wallet")setTimeout(()=>document.querySelector('[data-page="wallet"]')?.click(),250)}
function checkout(){if(!$("payWallet")||$("walletPage"))return;css();$("topupAmount")?.closest(".card")?.insertAdjacentHTML("afterbegin",`<div class="mw-note">Depo MonCash/NatCash fèt manyèlman nan Portefeuille. Admin dwe valide li.</div>`);$("payWallet")?.closest(".card")?.insertAdjacentHTML("beforeend",`<div class="mw-note">📦 Apre peman, kòmand lan ap tann validasyon admin.</div>`);document.addEventListener("click",e=>{if(!e.target.closest?.("#topupMoncash,#topupNatcash,#verifyTopup"))return;e.preventDefault();e.stopImmediatePropagation();location.href="./index.html#wallet"},true)}
async function adminOK(){const u=auth.currentUser;if(!u)return false;const s=await getDoc(doc(db,"users",u.uid));return s.exists()&&String(s.data().role||"").toLowerCase()==="admin"}
function adminUI(){const d=$("adminDashboard");if(!d||$("mwAdmin"))return;css();modal();d.insertAdjacentHTML("afterbegin",`<section id="mwAdmin" class="mw-admin"><h2>✅ Apwobasyon Admin</h2><p>Se sèlman admin ki ka valide/refize kòmand, depo ak retrè.</p><button id="mwRefresh" class="ghost">Rafraichi</button><div class="mw-grid"><div><h3>Depo / retrè an atant</h3><div id="mwAdminTx"></div></div><div><h3>Kòmand pou valide</h3><div id="mwAdminOrders"></div></div></div></section>`);$("mwRefresh").onclick=loadAdmin;document.addEventListener("click",actions);onAuthStateChanged(auth,u=>{if(u)setTimeout(loadAdmin,300)})}
async function loadAdmin(){if(!(await adminOK()))return;const [ts,os]=await Promise.all([getDocs(query(collection(db,"manualTransactions"),limit(250))),getDocs(query(collection(db,"orders"),limit(350)))]),ta=ts.docs.map(d=>({id:d.id,...d.data()})).filter(x=>(x.status||"pending")==="pending"),oa=os.docs.map(d=>({id:d.id,...d.data()})).filter(x=>!["completed","rejected"].includes(String(x.status||"").toLowerCase()));$("mwAdminTx").innerHTML=ta.length?ta.map(x=>`<div class="mw-a"><b>${x.type==="deposit"?"⬇️ Depo":"⬆️ Retrè"} ${esc((x.provider||"").toUpperCase())}</b><p>${esc(x.userName||x.userEmail||x.userId)} · ${money(x.amount)}</p><p>${x.type==="deposit"?`Soti: ${esc(x.senderPhone||"—")} · Ref: ${esc(x.reference||"—")}`:`Pou: ${esc(x.phone||"—")}`}</p><div class="mw-actions">${x.proofDataUrl?`<button class="proof" data-proof="${esc(x.id)}">Gade prèv</button>`:""}<button class="ok" data-ta="${esc(x.id)}">Apwouve</button><button class="no" data-tr="${esc(x.id)}">Refize</button></div></div>`).join(""):"Pa gen demann.";window.__mwproof=Object.fromEntries(ta.map(x=>[x.id,x.proofDataUrl||""]));$("mwAdminOrders").innerHTML=oa.length?oa.map(o=>`<div class="mw-a"><b>📦 ${esc(o.id)}</b><p>${esc(o.buyerName||o.buyerEmail||o.buyerId||"Client")}</p><p>${esc(o.status||"pending")} · ${esc(o.currency||"HTG")} ${(Number(o.total)||0).toLocaleString()}</p><div class="mw-actions"><button class="ok" data-oa="${esc(o.id)}">Apwouve</button><button class="no" data-or="${esc(o.id)}">Refize</button></div></div>`).join(""):"Pa gen kòmand."}
async function actions(e){const p=e.target.closest?.("[data-proof]");if(p){const src=window.__mwproof?.[p.dataset.proof];if(src){$("mwProofImg").src=src;$("mwProofModal").classList.add("open")}return}const a=e.target.closest?.("[data-ta]"),r=e.target.closest?.("[data-tr]"),oa=e.target.closest?.("[data-oa]"),or=e.target.closest?.("[data-or]");try{if(a)await approveTx(a.dataset.ta);else if(r)await updateDoc(doc(db,"manualTransactions",r.dataset.tr),{status:"rejected",rejectedAt:serverTimestamp(),rejectedBy:auth.currentUser.uid});else if(oa)await updateDoc(doc(db,"orders",oa.dataset.oa),{status:"completed",adminApproval:"approved",approvedAt:serverTimestamp(),approvedBy:auth.currentUser.uid});else if(or)await updateDoc(doc(db,"orders",or.dataset.or),{status:"rejected",adminApproval:"rejected",rejectedAt:serverTimestamp(),rejectedBy:auth.currentUser.uid});else return;await loadAdmin()}catch(x){console.error(x);alert(x.message||"Aksyon an echwe.")}}
async function approveTx(id){if(!(await adminOK()))throw Error("Aksè admin obligatwa.");const ref=doc(db,"manualTransactions",id);await runTransaction(db,async t=>{const s=await t.get(ref);if(!s.exists())throw Error("Demann lan pa egziste.");const x=s.data();if(x.status!=="pending")throw Error("Demann deja trete.");const ur=doc(db,"users",x.userId),us=await t.get(ur);if(!us.exists())throw Error("Kliyan pa egziste.");const u=us.data(),cur=Number(u.balances?.HTG??u.balance??0),amt=Number(x.amount)||0;if(x.type==="withdrawal"&&cur<amt)throw Error("Balans kliyan an pa sifi.");const next=x.type==="deposit"?cur+amt:cur-amt;t.update(ur,{"balances.HTG":next,balance:next});t.update(ref,{status:"approved",approvedAt:serverTimestamp(),approvedBy:auth.currentUser.uid})})}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>{if($("adminDashboard"))adminUI();else if($("walletPage"))client();checkout()},{once:true});else{if($("adminDashboard"))adminUI();else if($("walletPage"))client();checkout()}
