import {getApps,getApp,initializeApp} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import {getAuth,onAuthStateChanged} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import {getFirestore,collection,addDoc,getDocs,getDoc,setDoc,doc,serverTimestamp,query,where,limit,onSnapshot} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";

const config={apiKey:"AIzaSyC3JebExbgH1n40wzpwNjtASmOPG1tuKIs",authDomain:"mystroshop-eab92.firebaseapp.com",projectId:"mystroshop-eab92",appId:"1:104073035061:web:59d2779f2db7a8a3be207c"};
const app=getApps().length?getApp():initializeApp(config),auth=getAuth(app),db=getFirestore(app);
const byId=id=>document.getElementById(id),clean=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const time=v=>v?.toDate?v.toDate().getTime():v?.seconds?v.seconds*1000:new Date(v||0).getTime()||0;
let adminTarget=null,stopMessages=null;

function addStyles(){if(byId("privateChatStyles"))return;const style=document.createElement("style");style.id="privateChatStyles";style.textContent=`.private-box{background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:14px}.private-box[hidden]{display:none!important}.private-head{display:flex;justify-content:space-between;align-items:center;gap:10px}.private-close{border:0;background:#f2f4f7;border-radius:10px;width:38px;height:38px;font-size:22px}.private-note{background:#eef4ff;color:#2643a2;padding:12px;border-radius:12px;margin-bottom:10px}.private-messages{height:300px;overflow:auto;background:#f8fafc;border-radius:12px;padding:10px}.private-message{padding:9px 11px;margin:7px 0;background:#fff;border-radius:12px;border:1px solid #e5e7eb}.private-message.mine{background:#eef2ff}.private-compose{display:flex;gap:8px;margin-top:10px}.private-compose input,.private-select{flex:1;padding:11px;border:1px solid #d0d5dd;border-radius:10px;min-width:0}.private-compose button,.private-open{border:0;border-radius:10px;background:#3159db;color:#fff;padding:10px 14px;font-weight:700}@media(max-width:620px){.private-compose{flex-wrap:wrap}.private-select{flex-basis:100%}}`;document.head.appendChild(style)}

function clientPage(){const page=byId("chatPage");if(!page)return;addStyles();page.innerHTML=`<div class="page-title"><h2>🔐 Chat prive ak Administrasyon</h2></div><div class="private-box"><div id="privateStatus" class="private-note">Se admin ki dwe chwazi ou epi louvri chat la anvan ou ka voye mesaj.</div><div id="privateMessages" class="private-messages"></div><div class="private-compose"><input id="privateInput" disabled placeholder="Ekri yon mesaj..."><button id="privateSend" disabled>Voye</button></div></div>`;byId("privateSend").onclick=sendClient;onAuthStateChanged(auth,user=>{if(user)watchClient(user.uid)})}
function watchClient(uid){onSnapshot(doc(db,"adminThreads",uid),snap=>{const active=snap.exists()&&snap.data().active===true;byId("privateInput").disabled=!active;byId("privateSend").disabled=!active;byId("privateStatus").textContent=active?"Chat prive aktif ak Administrasyon Mystro-Shop.":"Se admin ki dwe chwazi ou epi louvri chat la anvan ou ka voye mesaj.";stopMessages?.();if(!active){byId("privateMessages").innerHTML="<p>Pa gen chat prive aktif.</p>";return}stopMessages=onSnapshot(query(collection(db,"privateMessages"),where("userId","==",uid),limit(200)),renderClientMessages)})}
function renderClientMessages(snapshot){const rows=snapshot.docs.map(d=>d.data()).sort((a,b)=>time(a.createdAt)-time(b.createdAt));byId("privateMessages").innerHTML=rows.map(m=>`<div class="private-message ${m.senderRole==="client"?"mine":""}"><b>${m.senderRole==="admin"?"Administrasyon Mystro-Shop":"Ou"}</b><br>${clean(m.text)}</div>`).join("")||"<p>Chat la louvri.</p>"}
async function sendClient(){const user=auth.currentUser,input=byId("privateInput"),text=input?.value.trim();if(!user||!text||input.disabled)return;await addDoc(collection(db,"privateMessages"),{threadId:user.uid,userId:user.uid,senderId:user.uid,senderRole:"client",text,createdAt:serverTimestamp()});input.value=""}

async function isAdmin(){const user=auth.currentUser;if(!user)return false;const snap=await getDoc(doc(db,"users",user.uid));return snap.exists()&&String(snap.data().role||"").toLowerCase()==="admin"}
function adminPage(){const dashboard=byId("adminDashboard");if(!dashboard)return;addStyles();dashboard.insertAdjacentHTML("afterbegin",`<section id="adminPrivateChat" class="private-box" style="margin-bottom:16px" hidden><div class="private-head"><h2>🔐 Chat prive Admin ↔ Kliyan</h2><button id="adminPrivateClose" class="private-close" type="button">×</button></div><p>Chwazi yon kliyan. Kliyan an pap wè idantite prive admin lan.</p><div class="private-compose"><select id="privateUserSelect" class="private-select"><option value="">— Chwazi kliyan —</option></select><button id="privateOpen" class="private-open">Louvri chat</button></div><div id="privateTarget" class="private-note">—</div><div id="adminPrivateMessages" class="private-messages"></div><div class="private-compose"><input id="adminPrivateInput" disabled placeholder="Ekri mesaj admin..."><button id="adminPrivateSend" disabled>Voye</button></div></section>`);byId("privateOpen").onclick=openAdminChat;byId("adminPrivateSend").onclick=sendAdmin;byId("adminPrivateClose").onclick=()=>toggleAdminChat(false);onAuthStateChanged(auth,user=>{if(user)setTimeout(loadUsers,300)});window.MystroAdminChat={open:()=>toggleAdminChat(true),close:()=>toggleAdminChat(false),toggle:()=>toggleAdminChat(byId("adminPrivateChat")?.hidden!==false)}}
function toggleAdminChat(show){const box=byId("adminPrivateChat");if(!box)return;box.hidden=!show;if(show)setTimeout(()=>box.scrollIntoView({behavior:"smooth",block:"start"}),50)}
async function loadUsers(){if(!(await isAdmin()))return;const snap=await getDocs(collection(db,"users"));const users=snap.docs.map(d=>({id:d.id,...d.data()})).filter(u=>String(u.role||"").toLowerCase()!=="admin"&&String(u.accountStatus||"active").toLowerCase()!=="deleted");byId("privateUserSelect").innerHTML='<option value="">— Chwazi kliyan —</option>'+users.map(u=>`<option value="${clean(u.id)}" data-name="${clean(u.name||u.displayName||u.email||"Client")}">${clean(u.name||u.displayName||u.email||"Client")}</option>`).join("")}
async function openAdminChat(){if(!(await isAdmin()))return;const select=byId("privateUserSelect"),uid=select.value;if(!uid)return;adminTarget={id:uid,name:select.selectedOptions[0].dataset.name||"Client"};await setDoc(doc(db,"adminThreads",uid),{userId:uid,active:true,openedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});byId("privateTarget").textContent="Kliyan: "+adminTarget.name;byId("adminPrivateInput").disabled=false;byId("adminPrivateSend").disabled=false;stopMessages?.();stopMessages=onSnapshot(query(collection(db,"privateMessages"),where("userId","==",uid),limit(200)),snap=>{const rows=snap.docs.map(d=>d.data()).sort((a,b)=>time(a.createdAt)-time(b.createdAt));byId("adminPrivateMessages").innerHTML=rows.map(m=>`<div class="private-message ${m.senderRole==="admin"?"mine":""}"><b>${m.senderRole==="admin"?"Administrasyon":"Kliyan"}</b><br>${clean(m.text)}</div>`).join("")||"<p>Ekri premye mesaj la.</p>"})}
async function sendAdmin(){if(!adminTarget||!(await isAdmin()))return;const input=byId("adminPrivateInput"),text=input?.value.trim();if(!text)return;await addDoc(collection(db,"privateMessages"),{threadId:adminTarget.id,userId:adminTarget.id,senderRole:"admin",text,createdAt:serverTimestamp()});input.value=""}

const ANSWERS={
ht:{buy:"Pou achte: ale nan Pwodwi, ajoute pwodwi a nan Panyen, epi ale nan Peman. Si balans ou pa sifi, fè yon depo nan Pòtfèy anvan.",sell:"Pou vann: ale nan Vann, mete non, kategori, pri, deviz, stock, deskripsyon ak 1–5 foto, epi pibliye pwodwi a.",deposit:"Pou depo MonCash/NatCash: ale nan Pòtfèy, chwazi Depo, mete montan, nimewo moun ki voye lajan an, referans ak foto prèv. Admin valide l anvan balans lan chanje.",withdraw:"Pou retrè: ale nan Pòtfèy, chwazi Retrè MonCash/NatCash, mete montan ak nimewo k ap resevwa a. Admin dwe valide demann lan.",order:"Nan Kòmand: pending_wallet_payment = poko peye; pending_admin = peye epi ap tann admin; completed = finalize.",password:"Sou ekran koneksyon an, itilize Modpas bliye pou resevwa yon imel reset.",language:"Chanje lang nan selektè lang ki anlè paj la. Mystro-Shop sipòte HT, FR, EN ak ES.",currency:"Chanje deviz nan selektè deviz ki anlè paj la. Pri yo ka afiche nan plizyè deviz.",chat:"Chat prive ak admin aktive sèlman lè administrasyon an chwazi kont ou epi louvri konvèsasyon an.",help:"Mwen reponn kestyon sou Mystro-Shop. Eseye: Kijan pou achte? Kijan pou fè depo? Kijan pou vann? Kote kòmand mwen? Kijan pou fè retrè?"},
fr:{buy:"Pour acheter : ouvrez Produits, ajoutez l’article au Panier puis ouvrez Paiement. Si le solde est insuffisant, faites d’abord un dépôt dans le Portefeuille.",sell:"Pour vendre : ouvrez Vendre, renseignez nom, catégorie, prix, devise, stock, description et 1 à 5 photos, puis publiez.",deposit:"Pour un dépôt MonCash/NatCash : ouvrez Portefeuille, choisissez Dépôt, indiquez montant, numéro d’envoi, référence et photo de preuve. L’admin valide avant crédit du solde.",withdraw:"Pour un retrait : ouvrez Portefeuille, choisissez Retrait MonCash/NatCash, indiquez le montant et le numéro destinataire. L’admin doit valider la demande.",order:"Dans Commandes : pending_wallet_payment = non payé; pending_admin = payé et en attente d’admin; completed = finalisé.",password:"Sur l’écran de connexion, utilisez Mot de passe oublié pour recevoir un e-mail de réinitialisation.",language:"Changez la langue avec le sélecteur en haut. Mystro-Shop prend en charge HT, FR, EN et ES.",currency:"Changez la devise avec le sélecteur en haut. Les prix peuvent être affichés dans plusieurs devises.",chat:"Le chat privé avec l’admin n’est actif que lorsque l’administration choisit votre compte et ouvre la conversation.",help:"Je réponds aux questions sur Mystro-Shop. Essayez : Comment acheter ? Comment faire un dépôt ? Comment vendre ? Où est ma commande ? Comment faire un retrait ?"},
en:{buy:"To buy: open Products, add an item to Cart, then open Payment. If your balance is low, deposit to Wallet first.",sell:"To sell: open Sell, enter name, category, price, currency, stock, description and 1–5 photos, then publish.",deposit:"For MonCash/NatCash deposit: open Wallet, choose Deposit, enter amount, sender number, reference and proof photo. Admin approval is required before crediting the balance.",withdraw:"For withdrawal: open Wallet, choose MonCash/NatCash Withdrawal, enter amount and receiving number. Admin approval is required.",order:"In Orders: pending_wallet_payment = unpaid; pending_admin = paid and waiting for admin; completed = finalized.",password:"Use Forgot password on the login screen to receive a reset email.",language:"Use the language selector at the top. Mystro-Shop supports HT, FR, EN and ES.",currency:"Use the currency selector at the top. Prices can display in multiple currencies.",chat:"Private admin chat is active only after administration selects your account and opens the conversation.",help:"I answer Mystro-Shop questions. Try: How do I buy? How do I deposit? How do I sell? Where is my order? How do I withdraw?"},
es:{buy:"Para comprar: abra Productos, agregue el artículo al Carrito y luego abra Pago. Si el saldo es insuficiente, deposite primero en la Cartera.",sell:"Para vender: abra Vender, indique nombre, categoría, precio, moneda, stock, descripción y 1–5 fotos, y publique.",deposit:"Para un depósito MonCash/NatCash: abra Cartera, elija Depósito, indique monto, número de envío, referencia y foto de prueba. El administrador debe aprobar antes de acreditar el saldo.",withdraw:"Para retirar: abra Cartera, elija Retiro MonCash/NatCash, indique monto y número receptor. El administrador debe aprobar la solicitud.",order:"En Pedidos: pending_wallet_payment = no pagado; pending_admin = pagado y esperando al administrador; completed = finalizado.",password:"Use Olvidé mi contraseña en la pantalla de acceso para recibir un correo de restablecimiento.",language:"Cambie el idioma con el selector superior. Mystro-Shop admite HT, FR, EN y ES.",currency:"Cambie la moneda con el selector superior. Los precios pueden mostrarse en varias monedas.",chat:"El chat privado con el administrador se activa solo cuando la administración selecciona su cuenta y abre la conversación.",help:"Respondo preguntas sobre Mystro-Shop. Pruebe: ¿Cómo comprar? ¿Cómo depositar? ¿Cómo vender? ¿Dónde está mi pedido? ¿Cómo retirar?"}
};
function assistantLang(){return byId("languageSelector")?.value||localStorage.getItem("mystroLang")||"fr"}
function norm(s){return String(s||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase()}
function smartReply(q){const x=norm(q),a=ANSWERS[assistantLang()]||ANSWERS.fr;if(/achet|buy|achte|comprar|panier|panyen|carrito/.test(x))return a.buy;if(/vann|vend|sell|publ|producto|produit/.test(x))return a.sell;if(/depo|deposit|depot|recharg|top.?up|moncash|natcash/.test(x)&&!/retrait|retire|withdraw|retiro/.test(x))return a.deposit;if(/retrait|retire|withdraw|retiro/.test(x))return a.withdraw;if(/k[oò]mand|commande|order|pedido|pending|apwouve|approve/.test(x))return a.order;if(/modpas|mot de passe|password|contrasena|reset/.test(x))return a.password;if(/lang|language|idioma|francais|kreyol|english|espanol/.test(x))return a.language;if(/deviz|devise|currency|moneda|usd|eur|htg/.test(x))return a.currency;if(/chat|mesaj|message|admin/.test(x))return a.chat;return a.help}
function pushAssistant(text,cls){const box=byId("assistantMessages");if(!box)return;box.insertAdjacentHTML("beforeend",`<div class="chat-message ${cls}">${clean(text)}</div>`);box.scrollTop=box.scrollHeight}
function enhanceAssistant(){const btn=byId("assistantSendBtn"),input=byId("assistantInput");if(!btn||!input||btn.dataset.smartAssistant)return;btn.dataset.smartAssistant="1";const send=e=>{e?.preventDefault();e?.stopImmediatePropagation();const q=input.value.trim();if(!q)return;pushAssistant(q,"user");input.value="";setTimeout(()=>pushAssistant(smartReply(q),"assistant"),80)};btn.addEventListener("click",send,true);input.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();e.stopImmediatePropagation();send(e)}},true)}

function start(){if(byId("adminDashboard"))adminPage();else if(byId("chatPage"))clientPage();enhanceAssistant()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
