import {getApps,getApp,initializeApp} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import {getAuth,onAuthStateChanged} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import {getFirestore,collection,addDoc,getDocs,getDoc,setDoc,doc,serverTimestamp,query,where,limit,onSnapshot} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";

const config={apiKey:"AIzaSyC3JebExbgH1n40wzpwNjtASmOPG1tuKIs",authDomain:"mystroshop-eab92.firebaseapp.com",projectId:"mystroshop-eab92",appId:"1:104073035061:web:59d2779f2db7a8a3be207c"};
const app=getApps().length?getApp():initializeApp(config);
const auth=getAuth(app),db=getFirestore(app);
const byId=id=>document.getElementById(id);
const clean=s=>String(s||"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;"}[c]));
const time=v=>v?.toDate?v.toDate().getTime():v?.seconds?v.seconds*1000:0;
let adminTarget=null,stopMessages=null;

function addStyles(){const style=document.createElement("style");style.textContent=".private-box{background:#fff;border:1px solid #e5e7eb;border-radius:18px;padding:14px}.private-note{background:#eef4ff;color:#2643a2;padding:12px;border-radius:12px;margin-bottom:10px}.private-messages{height:300px;overflow:auto;background:#f8fafc;border-radius:12px;padding:10px}.private-message{padding:9px 11px;margin:7px 0;background:#fff;border-radius:12px;border:1px solid #e5e7eb}.private-message.mine{background:#eef2ff}.private-compose{display:flex;gap:8px;margin-top:10px}.private-compose input,.private-select{flex:1;padding:11px;border:1px solid #d0d5dd;border-radius:10px}.private-compose button,.private-open{border:0;border-radius:10px;background:#3159db;color:#fff;padding:10px 14px;font-weight:700}";document.head.appendChild(style)}

function clientPage(){const page=byId("chatPage");if(!page)return;addStyles();page.innerHTML=`<div class="page-title"><h2>🔐 Chat prive ak Administrasyon</h2></div><div class="private-box"><div id="privateStatus" class="private-note">Se admin ki dwe chwazi ou epi louvri chat la anvan ou ka voye mesaj.</div><div id="privateMessages" class="private-messages"></div><div class="private-compose"><input id="privateInput" disabled placeholder="Ekri yon mesaj..."><button id="privateSend" disabled>Voye</button></div></div>`;byId("privateSend").onclick=sendClient;onAuthStateChanged(auth,user=>{if(user)watchClient(user.uid)})}
function watchClient(uid){onSnapshot(doc(db,"adminThreads",uid),snap=>{const active=snap.exists()&&snap.data().active===true;byId("privateInput").disabled=!active;byId("privateSend").disabled=!active;byId("privateStatus").textContent=active?"Chat prive aktif ak Administrasyon Mystro-Shop.":"Se admin ki dwe chwazi ou epi louvri chat la anvan ou ka voye mesaj.";stopMessages?.();if(!active){byId("privateMessages").innerHTML="<p>Pa gen chat prive aktif.</p>";return}stopMessages=onSnapshot(query(collection(db,"privateMessages"),where("userId","==",uid),limit(200)),renderClientMessages)})}
function renderClientMessages(snapshot){const rows=snapshot.docs.map(d=>d.data()).sort((a,b)=>time(a.createdAt)-time(b.createdAt));byId("privateMessages").innerHTML=rows.map(m=>`<div class="private-message ${m.senderRole==="client"?"mine":""}"><b>${m.senderRole==="admin"?"Administrasyon Mystro-Shop":"Ou"}</b><br>${clean(m.text)}</div>`).join("")||"<p>Chat la louvri.</p>"}
async function sendClient(){const user=auth.currentUser,input=byId("privateInput"),text=input.value.trim();if(!user||!text||input.disabled)return;await addDoc(collection(db,"privateMessages"),{threadId:user.uid,userId:user.uid,senderId:user.uid,senderRole:"client",text,createdAt:serverTimestamp()});input.value=""}

async function isAdmin(){const user=auth.currentUser;if(!user)return false;const snap=await getDoc(doc(db,"users",user.uid));return snap.exists()&&snap.data().role==="admin"}
function adminPage(){const dashboard=byId("adminDashboard");if(!dashboard)return;addStyles();dashboard.insertAdjacentHTML("afterbegin",`<section class="private-box" style="margin-bottom:16px"><h2>🔐 Chat prive Admin ↔ Kliyan</h2><p>Chwazi yon kliyan. Kliyan an pap wè idantite prive admin lan.</p><div class="private-compose"><select id="privateUserSelect" class="private-select"><option value="">— Chwazi kliyan —</option></select><button id="privateOpen" class="private-open">Louvri chat</button></div><div id="privateTarget" class="private-note">—</div><div id="adminPrivateMessages" class="private-messages"></div><div class="private-compose"><input id="adminPrivateInput" disabled placeholder="Ekri mesaj admin..."><button id="adminPrivateSend" disabled>Voye</button></div></section>`);byId("privateOpen").onclick=openAdminChat;byId("adminPrivateSend").onclick=sendAdmin;onAuthStateChanged(auth,user=>{if(user)setTimeout(loadUsers,300)})}
async function loadUsers(){if(!(await isAdmin()))return;const snap=await getDocs(collection(db,"users"));const users=snap.docs.map(d=>({id:d.id,...d.data()})).filter(u=>u.role!=="admin");byId("privateUserSelect").innerHTML='<option value="">— Chwazi kliyan —</option>'+users.map(u=>`<option value="${clean(u.id)}" data-name="${clean(u.name||u.email||"Client")}">${clean(u.name||u.email||"Client")}</option>`).join("")}
async function openAdminChat(){if(!(await isAdmin()))return;const select=byId("privateUserSelect"),uid=select.value;if(!uid)return;adminTarget={id:uid,name:select.selectedOptions[0].dataset.name||"Client"};await setDoc(doc(db,"adminThreads",uid),{userId:uid,active:true,openedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});byId("privateTarget").textContent="Kliyan: "+adminTarget.name;byId("adminPrivateInput").disabled=false;byId("adminPrivateSend").disabled=false;stopMessages?.();stopMessages=onSnapshot(query(collection(db,"privateMessages"),where("userId","==",uid),limit(200)),snap=>{const rows=snap.docs.map(d=>d.data()).sort((a,b)=>time(a.createdAt)-time(b.createdAt));byId("adminPrivateMessages").innerHTML=rows.map(m=>`<div class="private-message ${m.senderRole==="admin"?"mine":""}"><b>${m.senderRole==="admin"?"Administrasyon":"Kliyan"}</b><br>${clean(m.text)}</div>`).join("")||"<p>Ekri premye mesaj la.</p>"})}
async function sendAdmin(){if(!adminTarget||!(await isAdmin()))return;const input=byId("adminPrivateInput"),text=input.value.trim();if(!text)return;await addDoc(collection(db,"privateMessages"),{threadId:adminTarget.id,userId:adminTarget.id,senderRole:"admin",text,createdAt:serverTimestamp()});input.value=""}
function start(){if(byId("adminDashboard"))adminPage();else if(byId("chatPage"))clientPage()}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",start,{once:true});else start();
