const JSON_H={"content-type":"application/json;charset=UTF-8"};
const APP_ORIGIN="https://castorlucjulesmichel.github.io";
const enc=new TextEncoder();
let svcCache={token:"",exp:0};
const j=(x,s=200,h={})=>new Response(JSON.stringify(x),{status:s,headers:{...JSON_H,...h}});
const b64u=b=>btoa(String.fromCharCode(...new Uint8Array(b))).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"");
function cors(req,env){const o=req.headers.get("Origin")||"";const allowed=env.APP_ORIGIN||APP_ORIGIN;return{"Access-Control-Allow-Origin":o===allowed?o:allowed,"Access-Control-Allow-Headers":"Content-Type, Authorization","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Vary":"Origin"};}
function fireVal(v){if(v===null)return{nullValue:null};if(typeof v==="boolean")return{booleanValue:v};if(typeof v==="number")return Number.isInteger(v)?{integerValue:String(v)}:{doubleValue:v};if(typeof v==="string")return{stringValue:v};if(Array.isArray(v))return{arrayValue:{values:v.map(fireVal)}};return{mapValue:{fields:Object.fromEntries(Object.entries(v).map(([k,x])=>[k,fireVal(x)]))}};}
function fields(o){return Object.fromEntries(Object.entries(o).map(([k,v])=>[k,fireVal(v)]));}
function un(v){if(!v)return null;if("stringValue"in v)return v.stringValue;if("integerValue"in v)return Number(v.integerValue);if("doubleValue"in v)return Number(v.doubleValue);if("booleanValue"in v)return v.booleanValue;if("timestampValue"in v)return v.timestampValue;if("arrayValue"in v)return(v.arrayValue.values||[]).map(un);if("mapValue"in v)return Object.fromEntries(Object.entries(v.mapValue.fields||{}).map(([k,x])=>[k,un(x)]));return null;}
function docData(d){return Object.fromEntries(Object.entries(d?.fields||{}).map(([k,v])=>[k,un(v)]));}
function docName(env,path){return`projects/${env.FIREBASE_PROJECT_ID}/databases/(default)/documents/${path}`;}
async function authUser(req,env){const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");if(!token)throw Error("AUTH_REQUIRED");const r=await fetch(`https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=${env.FIREBASE_WEB_API_KEY}`,{method:"POST",headers:JSON_H,body:JSON.stringify({idToken:token})});const d=await r.json();if(!r.ok||!d.users?.[0])throw Error("AUTH_INVALID");return{uid:d.users[0].localId,email:d.users[0].email||""};}
function pemBuf(pem){const s=pem.replace(/\\n/g,"\n").replace(/-----[^-]+-----/g,"").replace(/\s/g,"");const raw=atob(s),u=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)u[i]=raw.charCodeAt(i);return u.buffer;}
async function serviceToken(env){if(svcCache.token&&Date.now()<svcCache.exp-60000)return svcCache.token;const now=Math.floor(Date.now()/1000),head=b64u(enc.encode(JSON.stringify({alg:"RS256",typ:"JWT"}))),pay=b64u(enc.encode(JSON.stringify({iss:env.FIREBASE_CLIENT_EMAIL,scope:"https://www.googleapis.com/auth/datastore",aud:"https://oauth2.googleapis.com/token",iat:now,exp:now+3500}))),key=await crypto.subtle.importKey("pkcs8",pemBuf(env.FIREBASE_PRIVATE_KEY),{name:"RSASSA-PKCS1-v1_5",hash:"SHA-256"},false,["sign"]),sig=await crypto.subtle.sign("RSASSA-PKCS1-v1_5",key,enc.encode(`${head}.${pay}`)),assertion=`${head}.${pay}.${b64u(sig)}`;const r=await fetch("https://oauth2.googleapis.com/token",{method:"POST",headers:{"content-type":"application/x-www-form-urlencoded"},body:new URLSearchParams({grant_type:"urn:ietf:params:oauth:grant-type:jwt-bearer",assertion})});const d=await r.json();if(!r.ok)throw Error("FIREBASE_SERVICE_AUTH");svcCache={token:d.access_token,exp:Date.now()+Number(d.expires_in||3500)*1000};return svcCache.token;}
async function fsGet(env,path){const token=await serviceToken(env),r=await fetch(`https://firestore.googleapis.com/v1/${docName(env,path)}`,{headers:{Authorization:`Bearer ${token}`}});if(r.status===404)return{exists:false,data:null,updateTime:null};const d=await r.json();if(!r.ok)throw Error(d.error?.message||"FIRESTORE_READ");return{exists:true,data:docData(d),updateTime:d.updateTime};}
function patchWrite(env,path,data,updateTime){return{update:{name:docName(env,path),fields:fields(data)},updateMask:{fieldPaths:Object.keys(data)},currentDocument:updateTime?{updateTime}:{exists:false}};}
async function fsCommit(env,writes){const token=await serviceToken(env),r=await fetch(`https://firestore.googleapis.com/v1/projects/${env.FIREBASE_PROJECT_ID}/databases/(default)/documents:commit`,{method:"POST",headers:{...JSON_H,Authorization:`Bearer ${token}`},body:JSON.stringify({writes})});const d=await r.json();if(!r.ok)throw Error(d.error?.message||"FIRESTORE_COMMIT");return d;}
function id(prefix="MS"){return`${prefix}${Date.now()}${Math.floor(Math.random()*900+100)}`;}
function rate(env,c){const m={HTG:1,USD:Number(env.FX_USD_HTG),EUR:Number(env.FX_EUR_HTG),CAD:Number(env.FX_CAD_HTG),GBP:Number(env.FX_GBP_HTG),DOP:Number(env.FX_DOP_HTG),XOF:Number(env.FX_XOF_HTG)};if(!Number.isFinite(m[c])||m[c]<=0)throw Error(`FX_${c}_NOT_CONFIGURED`);return m[c];}
async function moncashToken(env){const live=env.MONCASH_MODE==="live",host=live?"https://moncashbutton.digicelgroup.com/Api":"https://sandbox.moncashbutton.digicelgroup.com/Api",r=await fetch(`${host}/oauth/token`,{method:"POST",headers:{Accept:"application/json",Authorization:`Basic ${btoa(`${env.MONCASH_CLIENT_ID}:${env.MONCASH_CLIENT_SECRET}`)}`,"content-type":"application/x-www-form-urlencoded"},body:"scope=read,write&grant_type=client_credentials"}),d=await r.json();if(!r.ok||!d.access_token)throw Error("MONCASH_AUTH");return{token:d.access_token,host,gate:live?"https://moncashbutton.digicelgroup.com/Moncash-middleware":"https://sandbox.moncashbutton.digicelgroup.com/Moncash-middleware"};}
async function moncashCreate(env,amount,orderId){const a=await moncashToken(env),r=await fetch(`${a.host}/v1/CreatePayment`,{method:"POST",headers:{...JSON_H,Accept:"application/json",Authorization:`Bearer ${a.token}`},body:JSON.stringify({amount,orderId})}),d=await r.json();const token=d.payment_token?.token;if(!r.ok||!token)throw Error(d.message||"MONCASH_CREATE");return`${a.gate}/Payment/Redirect?token=${encodeURIComponent(token)}`;}
async function moncashVerify(env,orderId){const a=await moncashToken(env),r=await fetch(`${a.host}/v1/RetrieveOrderPayment`,{method:"POST",headers:{...JSON_H,Accept:"application/json",Authorization:`Bearer ${a.token}`},body:JSON.stringify({orderId})}),d=await r.json();if(!r.ok)throw Error(d.message||"MONCASH_VERIFY");return{paid:String(d.payment?.message||"").toLowerCase()==="successful",amount:Number(d.payment?.cost)||0,tx:d.payment?.transaction_id||""};}
async function paymCreate(env,amount,method,reference){if(!env.PAYM_CLIENT_ID)throw Error("PAYM_NOT_CONFIGURED");amount=Math.ceil(amount);if(amount<20)throw Error("MINIMUM_20_HTG");const r=await fetch(`${env.PAYM_BASE_URL||"https://plopplop.solutionip.app"}/api/paiement-marchand`,{method:"POST",headers:JSON_H,body:JSON.stringify({client_id:env.PAYM_CLIENT_ID,refference_id:reference,montant:amount,payment_method:method})}),d=await r.json();if(!r.ok||!d.url)throw Error(d.message||"PAYM_CREATE");return d.url;}
async function paymVerify(env,reference){const r=await fetch(`${env.PAYM_BASE_URL||"https://plopplop.solutionip.app"}/api/paiement-verify`,{method:"POST",headers:JSON_H,body:JSON.stringify({client_id:env.PAYM_CLIENT_ID,refference_id:reference})}),d=await r.json();if(!r.ok)throw Error(d.message||"PAYM_VERIFY");return{paid:d.trans_status==="ok",amount:Number(d.montant)||0,tx:d.id_transaction||""};}
async function createTopup(req,env,provider){const u=await authUser(req,env),b=await req.json(),amount=Math.ceil(Number(b.amount));if(!Number.isFinite(amount)||amount<20)throw Error("MINIMUM_20_HTG");const ref=id(provider==="moncash"?"MC":"NC"),now=new Date().toISOString();await fsCommit(env,[patchWrite(env,`topups/${ref}`,{userId:u.uid,provider,amount,status:"pending",createdAt:now},null)]);const redirectUrl=provider==="moncash"?await moncashCreate(env,amount,ref):await paymCreate(env,amount,"natcash",ref);return{reference:ref,redirectUrl};}
async function verifyTopup(req,env,provider){const u=await authUser(req,env),b=await req.json(),ref=String(b.reference||"");const t=await fsGet(env,`topups/${ref}`);if(!t.exists||t.data.userId!==u.uid||t.data.provider!==provider)throw Error("TOPUP_NOT_FOUND");if(t.data.status==="paid")return{ok:true,already:true};const p=provider==="moncash"?await moncashVerify(env,ref):await paymVerify(env,ref);if(!p.paid||p.amount+0.001<Number(t.data.amount))return{ok:false,status:"pending"};const user=await fsGet(env,`users/${u.uid}`);if(!user.exists)throw Error("USER_PROFILE_NOT_FOUND");const now=new Date().toISOString();await fsCommit(env,[patchWrite(env,`users/${u.uid}`,{balance:(Number(user.data.balance)||0)+Number(t.data.amount)},user.updateTime),patchWrite(env,`topups/${ref}`,{status:"paid",providerTransactionId:String(p.tx),paidAt:now},t.updateTime)]);return{ok:true,credited:Number(t.data.amount)};}
async function createOrder(req,env){const u=await authUser(req,env),b=await req.json(),src=Array.isArray(b.items)?b.items:[];if(!src.length)throw Error("EMPTY_CART");let subtotal=0,units=0;const items=[];for(const x of src){const qty=Math.max(1,Math.min(99,Math.floor(Number(x.qty)||1))),p=await fsGet(env,`products/${String(x.productId||"")}`);if(!p.exists||p.data.status==="inactive")throw Error("PRODUCT_UNAVAILABLE");const base=(Number(p.data.price)||0)*(1-Math.max(0,Math.min(90,Number(p.data.discountPercent)||0))/100),unit=Math.round(base*rate(env,p.data.currency||"HTG")*100)/100,line=Math.round(unit*qty*100)/100;subtotal+=line;units+=qty;items.push({productId:String(x.productId),name:String(p.data.name||"Produit"),sellerId:String(p.data.sellerId||""),category:String(p.data.category||""),qty,unitPrice:unit,lineTotal:line});}subtotal=Math.round(subtotal*100)/100;const commission=Math.round(subtotal*.10*100)/100,sellerAmount=Math.round((subtotal-commission)*100)/100,delivery=b.deliveryRequested?1000*units:0,total=subtotal+delivery,orderId=id("ORD"),now=new Date().toISOString();await fsCommit(env,[patchWrite(env,`orders/${orderId}`,{buyerId:u.uid,buyerEmail:u.email,items,currency:"HTG",subtotal,commissionRate:.10,commissionAmount:commission,sellerAmount,deliveryRequested:!!b.deliveryRequested,deliveryFee:delivery,total,paymentMethod:"mystro",status:"pending_wallet_payment",createdAt:now},null)]);return{orderId,currency:"HTG",subtotal,commissionAmount:commission,sellerAmount,deliveryFee:delivery,total};}
async function payOrder(req,env){const u=await authUser(req,env),b=await req.json(),orderId=String(b.orderId||""),o=await fsGet(env,`orders/${orderId}`);if(!o.exists||o.data.buyerId!==u.uid)throw Error("ORDER_NOT_FOUND");if(o.data.status==="paid")return{ok:true,already:true};if(o.data.status!=="pending_wallet_payment")throw Error("ORDER_NOT_PAYABLE");const buyer=await fsGet(env,`users/${u.uid}`),total=Number(o.data.total)||0;if(!buyer.exists)throw Error("USER_PROFILE_NOT_FOUND");if((Number(buyer.data.balance)||0)<total)throw Error("INSUFFICIENT_WALLET_BALANCE");const credits={};for(const it of o.data.items||[]){const sid=String(it.sellerId||"");if(!sid)throw Error("SELLER_MISSING");credits[sid]=(credits[sid]||0)+(Number(it.lineTotal)||0)*.90;}const writes=[patchWrite(env,`users/${u.uid}`,{balance:(Number(buyer.data.balance)||0)-total},buyer.updateTime)];for(const[sid,amt]of Object.entries(credits)){const s=await fsGet(env,`users/${sid}`);if(!s.exists)throw Error("SELLER_PROFILE_NOT_FOUND");writes.push(patchWrite(env,`users/${sid}`,{balance:(Number(s.data.balance)||0)+Math.round(amt*100)/100},s.updateTime));}const pf=await fsGet(env,"platform/finance"),commission=Number(o.data.commissionAmount)||0,delivery=Number(o.data.deliveryFee)||0;writes.push(patchWrite(env,"platform/finance",{commissionBalance:(Number(pf.data?.commissionBalance)||0)+commission,deliveryBalance:(Number(pf.data?.deliveryBalance)||0)+delivery,grossProductSales:(Number(pf.data?.grossProductSales)||0)+(Number(o.data.subtotal)||0)},pf.updateTime));writes.push(patchWrite(env,`orders/${orderId}`,{status:"paid",paidAt:new Date().toISOString()},o.updateTime));await fsCommit(env,writes);return{ok:true,orderId,total,commission,delivery};}
async function route(req,env){const url=new URL(req.url),p=url.pathname;if(req.method==="GET"&&p==="/")return{service:"Mystro-Shop API",ok:true};if(req.method!=="POST")throw Error("NOT_FOUND");if(p==="/moncash/deposit")return createTopup(req,env,"moncash");if(p==="/moncash/verify")return verifyTopup(req,env,"moncash");if(p==="/natcash/deposit")return createTopup(req,env,"natcash");if(p==="/natcash/verify")return verifyTopup(req,env,"natcash");if(p==="/orders/create")return createOrder(req,env);if(p==="/wallet/pay-order")return payOrder(req,env);throw Error("NOT_FOUND");}
export default{async fetch(req,env){const h=cors(req,env);if(req.method==="OPTIONS")return new Response(null,{status:204,headers:h});try{return j(await route(req,env),200,h)}catch(e){const m=String(e.message||e),map={AUTH_REQUIRED:401,AUTH_INVALID:401,NOT_FOUND:404,INSUFFICIENT_WALLET_BALANCE:409,ORDER_NOT_FOUND:404,TOPUP_NOT_FOUND:404,MINIMUM_20_HTG:400};return j({ok:false,error:m},map[m]||400,h)}}};