import {firebaseConfig} from "./firebase-config.js";
import {initializeApp} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-app.js";
import {getAuth,onAuthStateChanged,signInWithPhoneNumber,RecaptchaVerifier,signOut} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-auth.js";
import {getFirestore,doc,getDoc,setDoc,addDoc,updateDoc,collection,query,where,onSnapshot,getDocs,orderBy,serverTimestamp,limit} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-firestore.js";
import {getStorage,ref,uploadBytes,getDownloadURL} from "https://www.gstatic.com/firebasejs/10.14.1/firebase-storage.js";

const fb=initializeApp(firebaseConfig),auth=getAuth(fb),db=getFirestore(fb),storage=getStorage(fb);
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const S={user:null,profile:{},admin:false,chat:null,cart:[],unsubs:[]};
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
const toast=t=>{const e=$("#toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2200)};
const norm=s=>String(s||"").trim().toLowerCase().replace(/[^a-z0-9_.-]/g,"");
const addUnsub=u=>{if(typeof u==="function")S.unsubs.push(u)};
const clearUnsubs=()=>{S.unsubs.forEach(u=>u());S.unsubs=[]};

function tab(n){$$(".tab").forEach(x=>x.classList.remove("active"));$$("nav button").forEach(x=>x.classList.remove("active"));$("#"+n+"Tab")?.classList.add("active");document.querySelector('nav button[data-tab="'+n+'"]')?.classList.add("active")}
$$("nav button[data-tab]").forEach(b=>b.onclick=()=>tab(b.dataset.tab));

async function recaptcha(){if(window.rc)return window.rc;window.rc=new RecaptchaVerifier(auth,"recaptcha-container",{size:"normal"});await window.rc.render();return window.rc}
$("#sendOtp").onclick=async()=>{try{const phone=$("#phone").value.trim();if(!phone.startsWith("+"))return toast("Mete +509...");S.confirm=await signInWithPhoneNumber(auth,phone,await recaptcha());$("#otpBox").classList.remove("hidden");toast("OTP voye")}catch(e){console.error(e);toast("OTP pa t voye")}};
$("#verifyOtp").onclick=async()=>{try{await S.confirm.confirm($("#otp").value.trim())}catch(e){toast("Kòd la pa valab")}};
$("#logout").onclick=()=>signOut(auth);

onAuthStateChanged(auth,async u=>{clearUnsubs();S.user=u;if(!u){$("#auth").classList.remove("hidden");$("#app").classList.add("hidden");return}
$("#auth").classList.add("hidden");$("#app").classList.remove("hidden");await ensureUser();await loadProfile();await detectAdmin();watchProducts();watchClips();watchRequests();watchChats();$("#who").textContent=S.profile.displayName||u.phoneNumber||""});

async function ensureUser(){const r=doc(db,"users",S.user.uid),s=await getDoc(r);if(!s.exists())await setDoc(r,{phone:S.user.phoneNumber||"",blocked:false,createdAt:serverTimestamp()});else if(s.data().blocked){toast("Kont sa bloke");await signOut(auth)}}
async function detectAdmin(){const t=await S.user.getIdTokenResult(true);S.admin=t.claims.admin===true;$("#adminNav").classList.toggle("hidden",!S.admin);if(S.admin)loadAdmin()}
async function loadProfile(){const s=await getDoc(doc(db,"publicProfiles",S.user.uid));S.profile=s.exists()?s.data():{};$("#displayName").value=S.profile.displayName||"";$("#username").value=S.profile.username||"";$("#bio").value=S.profile.bio||""}
$("#profileForm").onsubmit=async e=>{e.preventDefault();const username=norm($("#username").value);if(username.length<3)return toast("Username twò kout");const q=query(collection(db,"publicProfiles"),where("username","==",username),limit(2)),m=await getDocs(q);if(m.docs.some(d=>d.id!==S.user.uid))return toast("Username deja pran");await setDoc(doc(db,"publicProfiles",S.user.uid),{displayName:$("#displayName").value.trim()||username,username,bio:$("#bio").value.trim(),updatedAt:serverTimestamp()},{merge:true});await loadProfile();toast("Profil sove")};

$("#showProductForm").onclick=()=>$("#productForm").classList.toggle("hidden");
$("#productForm").onsubmit=async e=>{e.preventDefault();try{let imageUrl="",f=$("#pImage").files[0];if(f){if(f.size>8*1024*1024)return toast("Foto twò gwo");const rr=ref(storage,"mystro-connect/products/"+S.user.uid+"/"+crypto.randomUUID()+"-"+f.name.replace(/[^a-zA-Z0-9._-]/g,"_"));const up=await uploadBytes(rr,f);imageUrl=await getDownloadURL(up.ref)}
await addDoc(collection(db,"products"),{sellerId:S.user.uid,sellerUsername:S.profile.username||"",name:$("#pName").value.trim(),price:Number($("#pPrice").value),currency:$("#pCurrency").value,description:$("#pDesc").value.trim(),imageUrl,active:true,createdAt:serverTimestamp()});e.target.reset();toast("Pwodwi pibliye")}catch(x){console.error(x);toast("Echèk piblikasyon")}};
function watchProducts(){addUnsub(onSnapshot(collection(db,"products"),s=>{const a=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.active!==false);$("#countProducts").textContent=a.length;$("#products").innerHTML=a.map(p=>'<article class="product">'+(p.imageUrl?'<img src="'+esc(p.imageUrl)+'">':'')+'<div class="body"><h3>'+esc(p.name)+'</h3><p>'+esc(p.description||"")+'</p><div class="price">'+esc(p.price)+" "+esc(p.currency||"HTG")+'</div></div></article>').join("")||'<p class="muted">Pa gen pwodwi.</p>'}))}

$("#showClipForm").onclick=()=>$("#clipForm").classList.toggle("hidden");
$("#clipForm").onsubmit=async e=>{e.preventDefault();try{const f=$("#clipFile").files[0];if(!f)return;if(f.size>80*1024*1024)return toast("Videyo twò gwo");const rr=ref(storage,"mystro-connect/clips/"+S.user.uid+"/"+crypto.randomUUID()+"-"+f.name.replace(/[^a-zA-Z0-9._-]/g,"_"));const up=await uploadBytes(rr,f),videoUrl=await getDownloadURL(up.ref);await addDoc(collection(db,"shortVideos"),{ownerId:S.user.uid,username:S.profile.username||"",caption:$("#clipCaption").value.trim(),videoUrl,active:true,createdAt:serverTimestamp()});e.target.reset();toast("Clip pibliye")}catch(x){console.error(x);toast("Clip pa pibliye")}};
function watchClips(){addUnsub(onSnapshot(collection(db,"shortVideos"),s=>{const a=s.docs.map(d=>({id:d.id,...d.data()})).filter(x=>x.active!==false);$("#countClips").textContent=a.length;$("#clips").innerHTML=a.map(v=>'<article class="clip"><video controls playsinline preload="metadata" src="'+esc(v.videoUrl)+'"></video><div class="overlay"><b>@'+esc(v.username||"user")+'</b><p>'+esc(v.caption||"")+'</p><button data-report="'+esc(v.id)+'">⚑ Rapòte</button></div></article>').join("");$$("[data-report]").forEach(b=>b.onclick=()=>reportCase("clip",b.dataset.report,"Videyo rapòte"))}))}

$("#requestForm").onsubmit=async e=>{e.preventDefault();try{await addDoc(collection(db,"requests"),{userId:S.user.uid,type:$("#requestType").value,amount:Number($("#requestAmount").value||0),currency:$("#requestCurrency").value,note:$("#requestNote").value.trim(),status:"pending",createdAt:serverTimestamp()});e.target.reset();toast("Demand voye")}catch(x){toast("Demand pa voye")}};
function watchRequests(){const q=query(collection(db,"requests"),where("userId","==",S.user.uid));addUnsub(onSnapshot(q,s=>{const a=s.docs.map(d=>({id:d.id,...d.data()}));$("#countRequests").textContent=a.length;$("#myRequests").innerHTML=a.map(r=>'<div class="card"><b>'+esc(r.type)+'</b> — '+esc(r.amount)+" "+esc(r.currency)+'<br><span class="muted">Estati: '+esc(r.status)+'</span></div>').join("")||'<p class="muted">Pa gen demand.</p>'}))}

$("#newChat").onclick=()=>$("#newChatBox").classList.toggle("hidden");
$("#startChat").onclick=async()=>{const un=norm($("#targetUsername").value),q=query(collection(db,"publicProfiles"),where("username","==",un),limit(1)),s=await getDocs(q);if(s.empty)return toast("Username pa jwenn");const o=s.docs[0];if(o.id===S.user.uid)return;const ids=[S.user.uid,o.id].sort(),id=ids.join("__");await setDoc(doc(db,"chats",id),{participants:ids,participantNames:{[S.user.uid]:S.profile.displayName||S.profile.username||"User",[o.id]:o.data().displayName||o.data().username||"User"},lastMessage:"",updatedAt:serverTimestamp()},{merge:true});openChat(id,o.data().displayName||un)};
function watchChats(){const q=query(collection(db,"chats"),where("participants","array-contains",S.user.uid));addUnsub(onSnapshot(q,s=>{const a=s.docs.map(d=>({id:d.id,...d.data()}));$("#chatList").innerHTML=a.map(c=>{const oid=c.participants.find(x=>x!==S.user.uid)||S.user.uid,n=c.participantNames?.[oid]||"Chat";return '<div class="chat-item" data-chat="'+esc(c.id)+'" data-name="'+esc(n)+'"><b>'+esc(n)+'</b><br><small>'+esc(c.lastMessage||"")+'</small></div>'}).join("");$$("[data-chat]").forEach(x=>x.onclick=()=>openChat(x.dataset.chat,x.dataset.name))}))}
function openChat(id,name){S.chat=id;$("#chatTitle").innerHTML=esc(name)+' <button id="reportChat" class="ghost">Rapòte</button>';$("#messageForm").classList.remove("hidden");$("#reportChat").onclick=()=>reportChat(id,name);const q=query(collection(db,"chats",id,"messages"),orderBy("createdAt","asc"),limit(200));addUnsub(onSnapshot(q,s=>{$("#messages").innerHTML=s.docs.map(d=>{const m=d.data();return '<div class="msg '+(m.senderId===S.user.uid?"me":"")+'">'+esc(m.text||"")+'</div>'}).join("");$("#messages").scrollTop=$("#messages").scrollHeight}))}
$("#messageForm").onsubmit=async e=>{e.preventDefault();const t=$("#messageText").value.trim();if(!t||!S.chat)return;await addDoc(collection(db,"chats",S.chat,"messages"),{senderId:S.user.uid,text:t,createdAt:serverTimestamp()});await updateDoc(doc(db,"chats",S.chat),{lastMessage:t.slice(0,100),updatedAt:serverTimestamp()});$("#messageText").value=""};
async function reportChat(id,name){const q=query(collection(db,"chats",id,"messages"),orderBy("createdAt","desc"),limit(20)),s=await getDocs(q),excerpt=s.docs.reverse().map(d=>({senderId:d.data().senderId,text:d.data().text||""}));await addDoc(collection(db,"moderationCases"),{reporterId:S.user.uid,type:"chat",targetId:id,title:"Chat ak "+name,excerpt,status:"open",createdAt:serverTimestamp()});toast("Chat la pataje ak moderasyon")}

async function reportCase(type,targetId,title){await addDoc(collection(db,"moderationCases"),{reporterId:S.user.uid,type,targetId,title,status:"open",createdAt:serverTimestamp()});toast("Rapò voye")}

async function loadAdmin(){if(!S.admin)return;try{const [us,vs,rs,cs]=await Promise.all([getDocs(collection(db,"users")),getDocs(collection(db,"shortVideos")),getDocs(collection(db,"requests")),getDocs(collection(db,"moderationCases"))]);$("#aUsers").textContent=us.size;$("#aClips").textContent=vs.size;$("#aPending").textContent=rs.docs.filter(d=>d.data().status==="pending").length;
$("#adminUsers").innerHTML=us.docs.map(d=>{const u=d.data();return '<div class="admin-row"><b>'+esc(u.phone||d.id)+'</b><br><span class="muted">'+(u.blocked?"Bloke":"Aktif")+'</span><div class="actions"><button data-block="'+d.id+'" data-next="'+(!u.blocked)+'">'+(u.blocked?"Debloke":"Bloke")+'</button></div></div>'}).join("");
$("#adminClips").innerHTML=vs.docs.map(d=>{const v=d.data();return '<div class="admin-row"><b>@'+esc(v.username||"user")+'</b><br><span>'+esc(v.caption||"")+'</span><div class="actions"><button data-video="'+d.id+'" data-active="'+(v.active!==false)+'">'+(v.active===false?"Reaktive":"Kache")+'</button></div></div>'}).join("");
$("#adminRequests").innerHTML=rs.docs.map(d=>{const r=d.data();return '<div class="admin-row"><b>'+esc(r.type)+'</b> — '+esc(r.amount)+" "+esc(r.currency)+'<br><span class="muted">'+esc(r.status)+'</span><div class="actions">'+(r.status==="pending"?'<button class="ok" data-req="'+d.id+'" data-status="approved">Valide</button><button class="danger" data-req="'+d.id+'" data-status="rejected">Rejte</button>':"")+'</div></div>'}).join("");
$("#adminCases").innerHTML=cs.docs.map(d=>{const c=d.data(),ex=Array.isArray(c.excerpt)?c.excerpt.map(x=>esc(x.text)).join("<br>"):"";return '<div class="admin-row"><b>'+esc(c.title||c.type)+'</b><div>'+ex+'</div><span class="muted">'+esc(c.status||"open")+'</span></div>'}).join("");
$$("[data-block]").forEach(b=>b.onclick=async()=>{await updateDoc(doc(db,"users",b.dataset.block),{blocked:b.dataset.next==="true",updatedAt:serverTimestamp()});loadAdmin()});
$$("[data-video]").forEach(b=>b.onclick=async()=>{await updateDoc(doc(db,"shortVideos",b.dataset.video),{active:b.dataset.active!=="true",updatedAt:serverTimestamp()});loadAdmin()});
$$("[data-req]").forEach(b=>b.onclick=async()=>{await updateDoc(doc(db,"requests",b.dataset.req),{status:b.dataset.status,reviewedBy:S.user.uid,reviewedAt:serverTimestamp()});loadAdmin()});
}catch(e){console.error(e);toast("Admin pa t chaje")}}
$("#reloadAdmin").onclick=loadAdmin;
